export type CefrLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1';

export interface VocabEntry {
  id: string;
  en: string;
  de: string;
  level: CefrLevel;
}

// ============================================================
// VOKABELN -- Business English, gruppiert nach CEFR-Niveau (A1-C1).
// Jedes Level baut auf den vorherigen auf (keine Ueberschneidungen).
// Weitere Vokabeln koennen einfach am Ende des jeweiligen Blocks
// ergaenzt werden -- die id wird automatisch aus Level + Position
// gebildet, muss also nicht manuell vergeben werden.
// ============================================================

const A1_WORDS: Omit<VocabEntry, 'id' | 'level'>[] = [
  { en: 'office', de: 'Büro' },
  { en: 'company', de: 'Firma / Unternehmen' },
  { en: 'business', de: 'Geschäft / Business' },
  { en: 'work', de: 'Arbeit' },
  { en: 'job', de: 'Job / Arbeit' },
  { en: 'boss', de: 'Chef(in)' },
  { en: 'manager', de: 'Manager(in) / Leiter(in)' },
  { en: 'team', de: 'Team' },
  { en: 'colleague', de: 'Kollege/Kollegin' },
  { en: 'customer', de: 'Kunde/Kundin' },
  { en: 'client', de: 'Kunde/Kundin (Business)' },
  { en: 'visitor', de: 'Besucher(in)' },
  { en: 'meeting', de: 'Meeting / Besprechung' },
  { en: 'appointment', de: 'Termin' },
  { en: 'plan', de: 'Plan' },
  { en: 'task', de: 'Aufgabe' },
  { en: 'project', de: 'Projekt' },
  { en: 'problem', de: 'Problem' },
  { en: 'solution', de: 'Lösung' },
  { en: 'idea', de: 'Idee' },
  { en: 'question', de: 'Frage' },
  { en: 'answer', de: 'Antwort' },
  { en: 'help', de: 'Hilfe' },
  { en: 'information', de: 'Information' },
  { en: 'details', de: 'Details / Einzelheiten' },
  { en: 'number', de: 'Zahl' },
  { en: 'date', de: 'Datum' },
  { en: 'time', de: 'Zeit / Uhrzeit' },
  { en: 'place', de: 'Ort' },
  { en: 'today', de: 'heute' },
  { en: 'tomorrow', de: 'morgen' },
  { en: 'now', de: 'jetzt' },
  { en: 'later', de: 'später' },
  { en: 'early', de: 'früh' },
  { en: 'late', de: 'spät' },
  { en: 'reception', de: 'Empfang' },
  { en: 'office room', de: 'Büroraum' },
  { en: 'meeting room', de: 'Besprechungsraum' },
  { en: 'desk', de: 'Schreibtisch' },
  { en: 'chair', de: 'Stuhl' },
  { en: 'kitchen', de: 'Küche' },
  { en: 'warehouse', de: 'Lager' },
  { en: 'shop', de: 'Laden / Geschäft' },
  { en: 'factory', de: 'Fabrik' },
  { en: 'head office', de: 'Hauptsitz' },
  { en: 'branch', de: 'Filiale / Niederlassung' },
  { en: 'sales department', de: 'Vertrieb / Verkaufsabteilung' },
  { en: 'marketing department', de: 'Marketingabteilung' },
  { en: 'HR (human resources)', de: 'Personalabteilung' },
  { en: 'finance department', de: 'Finanzabteilung' },
  { en: 'accounting', de: 'Buchhaltung' },
  { en: 'customer service', de: 'Kundenservice' },
  { en: 'IT department', de: 'IT-Abteilung' },
  { en: 'production', de: 'Produktion' },
  { en: 'management', de: 'Geschäftsleitung / Management' },
  { en: 'computer', de: 'Computer' },
  { en: 'laptop', de: 'Laptop' },
  { en: 'phone', de: 'Telefon / Handy' },
  { en: 'printer', de: 'Drucker' },
  { en: 'screen', de: 'Bildschirm' },
  { en: 'keyboard', de: 'Tastatur' },
  { en: 'mouse', de: 'Maus' },
  { en: 'paper', de: 'Papier' },
  { en: 'pen', de: 'Stift' },
  { en: 'notebook', de: 'Notizbuch' },
  { en: 'file', de: 'Datei / Akte' },
  { en: 'folder', de: 'Ordner' },
  { en: 'document', de: 'Dokument' },
  { en: 'form', de: 'Formular' },
  { en: 'letter', de: 'Brief' },
  { en: 'email', de: 'E-Mail' },
  { en: 'message', de: 'Nachricht' },
  { en: 'report', de: 'Bericht / Report' },
  { en: 'list', de: 'Liste' },
  { en: 'table', de: 'Tabelle' },
  { en: 'chart', de: 'Diagramm' },
  { en: 'picture', de: 'Bild' },
  { en: 'copy', de: 'Kopie' },
  { en: 'stamp', de: 'Stempel' },
  { en: 'to work', de: 'arbeiten' },
  { en: 'to do', de: 'machen / tun' },
  { en: 'to make', de: 'machen / herstellen' },
  { en: 'to have', de: 'haben' },
  { en: 'to be', de: 'sein' },
  { en: 'to need', de: 'brauchen' },
  { en: 'to want', de: 'wollen' },
  { en: 'to ask', de: 'fragen' },
  { en: 'to answer', de: 'antworten' },
  { en: 'to tell', de: 'sagen / mitteilen' },
  { en: 'to say', de: 'sagen' },
  { en: 'to call', de: 'anrufen' },
  { en: 'to send', de: 'senden / schicken' },
  { en: 'to get', de: 'bekommen / erhalten' },
  { en: 'to give', de: 'geben' },
  { en: 'to take', de: 'nehmen' },
  { en: 'to use', de: 'benutzen' },
  { en: 'to open', de: 'öffnen' },
  { en: 'to close', de: 'schließen' },
  { en: 'to read', de: 'lesen' },
  { en: 'to write', de: 'schreiben' },
  { en: 'to check', de: 'prüfen / checken' },
  { en: 'to find', de: 'finden' },
  { en: 'to show', de: 'zeigen' },
  { en: 'to start', de: 'starten / anfangen' },
  { en: 'to finish', de: 'beenden / fertig machen' },
  { en: 'to plan', de: 'planen' },
  { en: 'to meet', de: 'treffen' },
  { en: 'to talk', de: 'sprechen' },
  { en: 'to pay', de: 'bezahlen' },
  { en: 'to buy', de: 'kaufen' },
  { en: 'to sell', de: 'verkaufen' },
  { en: 'to order', de: 'bestellen' },
  { en: 'to deliver', de: 'liefern' },
  { en: 'to agree', de: 'zustimmen' },
  { en: 'to change', de: 'ändern' },
  { en: 'to cancel', de: 'absagen / stornieren' },
  { en: 'to sign', de: 'unterschreiben' },
  { en: 'to share', de: 'teilen' },
  { en: 'money', de: 'Geld' },
  { en: 'price', de: 'Preis' },
  { en: 'cost', de: 'Kosten' },
  { en: 'discount', de: 'Rabatt' },
  { en: 'bill', de: 'Rechnung' },
  { en: 'invoice', de: 'Rechnung (Business)' },
  { en: 'payment', de: 'Zahlung' },
  { en: 'cash', de: 'Bargeld' },
  { en: 'card', de: 'Karte (EC/Kreditkarte)' },
  { en: 'bank', de: 'Bank' },
  { en: 'account', de: 'Konto' },
  { en: 'budget', de: 'Budget' },
  { en: 'cheap', de: 'günstig' },
  { en: 'expensive', de: 'teuer' },
  { en: 'free', de: 'kostenlos' },
  { en: 'total', de: 'Gesamt / insgesamt' },
  { en: 'per day', de: 'pro Tag' },
  { en: 'per week', de: 'pro Woche' },
  { en: 'per month', de: 'pro Monat' },
  { en: 'per year', de: 'pro Jahr' },
  { en: 'product', de: 'Produkt' },
  { en: 'service', de: 'Dienstleistung' },
  { en: 'item', de: 'Artikel' },
  { en: 'order', de: 'Bestellung / Auftrag' },
  { en: 'quote / quotation', de: 'Angebot (Preisangebot)' },
  { en: 'supplier', de: 'Lieferant(in)' },
  { en: 'delivery', de: 'Lieferung' },
  { en: 'delivery date', de: 'Lieferdatum' },
  { en: 'stock', de: 'Bestand / Lagerbestand' },
  { en: 'in stock', de: 'auf Lager' },
  { en: 'out of stock', de: 'nicht auf Lager' },
  { en: 'quality', de: 'Qualität' },
  { en: 'warranty', de: 'Garantie' },
  { en: 'return', de: 'Rückgabe' },
  { en: 'to return', de: 'zurückgeben' },
  { en: 'to replace', de: 'ersetzen' },
  { en: 'complaint', de: 'Beschwerde' },
  { en: 'support', de: 'Unterstützung / Support' },
  { en: 'request', de: 'Anfrage / Bitte' },
  { en: 'feedback', de: 'Feedback / Rückmeldung' },
  { en: 'address', de: 'Adresse' },
  { en: 'phone number', de: 'Telefonnummer' },
  { en: 'email address', de: 'E-Mail-Adresse' },
  { en: 'contact', de: 'Kontakt' },
  { en: 'sorry', de: 'entschuldigung / tut mir leid' },
  { en: 'thank you', de: 'danke' },
  { en: 'you\'re welcome', de: 'gern geschehen' },
  { en: 'please', de: 'bitte' },
  { en: 'urgent', de: 'dringend' },
  { en: 'important', de: 'wichtig' },
  { en: 'subject', de: 'Betreff' },
  { en: 'attachment', de: 'Anhang' },
  { en: 'link', de: 'Link' },
  { en: 'to attach', de: 'anhängen' },
  { en: 'to reply', de: 'antworten' },
  { en: 'reply all', de: 'allen antworten' },
  { en: 'to forward', de: 'weiterleiten' },
  { en: 'draft', de: 'Entwurf' },
  { en: 'inbox', de: 'Posteingang' },
  { en: 'outbox', de: 'Postausgang' },
  { en: 'spam', de: 'Spam' },
  { en: 'signature', de: 'Signatur' },
  { en: 'greeting', de: 'Begrüßung' },
  { en: 'closing', de: 'Grußformel' },
  { en: 'topic', de: 'Thema' },
  { en: 'goal', de: 'Ziel' },
  { en: 'result', de: 'Ergebnis' },
  { en: 'summary', de: 'Zusammenfassung' },
  { en: 'introduction', de: 'Einleitung' },
  { en: 'conclusion', de: 'Fazit / Schluss' },
  { en: 'example', de: 'Beispiel' },
  { en: 'point', de: 'Punkt' },
  { en: 'part', de: 'Teil' },
  { en: 'main', de: 'Haupt-' },
  { en: 'simple', de: 'einfach' },
  { en: 'clear', de: 'klar' },
  { en: 'next step', de: 'nächster Schritt' },
  { en: 'progress', de: 'Fortschritt' },
  { en: 'status', de: 'Status' },
  { en: 'recommendation', de: 'Empfehlung' },
  { en: 'data', de: 'Daten' },
  { en: 'marketing', de: 'Marketing' },
  { en: 'market', de: 'Markt' },
  { en: 'target group', de: 'Zielgruppe' },
  { en: 'brand', de: 'Marke' },
  { en: 'logo', de: 'Logo' },
  { en: 'ad / advertisement', de: 'Werbung / Anzeige' },
  { en: 'campaign', de: 'Kampagne' },
  { en: 'social media', de: 'soziale Medien' },
  { en: 'website', de: 'Webseite' },
  { en: 'poster', de: 'Plakat' },
  { en: 'flyer', de: 'Flyer' },
  { en: 'offer', de: 'Angebot' },
  { en: 'design', de: 'Design / Gestaltung' },
  { en: 'message (marketing)', de: 'Botschaft' },
  { en: 'to promote', de: 'bewerben' },
  { en: 'to advertise', de: 'werben' },
  { en: 'new', de: 'neu' },
  { en: 'popular', de: 'beliebt' },
  { en: 'customer needs', de: 'Kundenbedürfnisse' },
  { en: 'sales', de: 'Vertrieb / Verkauf' },
  { en: 'sale', de: 'Verkauf' },
  { en: 'seller', de: 'Verkäufer(in)' },
  { en: 'buyer', de: 'Käufer(in)' },
  { en: 'call', de: 'Anruf' },
  { en: 'contract', de: 'Vertrag' },
  { en: 'deal', de: 'Deal / Geschäft' },
  { en: 'staff', de: 'Personal / Mitarbeitende' },
  { en: 'employee', de: 'Mitarbeiter(in)' },
  { en: 'worker', de: 'Arbeiter(in)' },
  { en: 'position', de: 'Position / Stelle' },
  { en: 'working hours', de: 'Arbeitszeiten' },
  { en: 'full-time', de: 'Vollzeit' },
  { en: 'part-time', de: 'Teilzeit' },
  { en: 'holiday', de: 'Urlaub' },
  { en: 'sick', de: 'krank' },
  { en: 'training', de: 'Training / Schulung' },
  { en: 'interview', de: 'Vorstellungsgespräch' },
  { en: 'applicant', de: 'Bewerber(in)' },
  { en: 'application', de: 'Bewerbung' },
  { en: 'CV', de: 'Lebenslauf' },
  { en: 'salary', de: 'Gehalt' },
  { en: 'to hire', de: 'einstellen' },
  { en: 'calendar', de: 'Kalender' },
  { en: 'schedule', de: 'Zeitplan' },
  { en: 'agenda', de: 'Agenda / Tagesordnung' },
  { en: 'minutes (meeting minutes)', de: 'Protokoll' },
  { en: 'note', de: 'Notiz' },
  { en: 'to confirm', de: 'bestätigen' },
  { en: 'on time', de: 'pünktlich' },
  { en: 'process', de: 'Prozess' },
  { en: 'step', de: 'Schritt' },
  { en: 'transport', de: 'Transport' },
  { en: 'package', de: 'Paket' },
  { en: 'to pack', de: 'verpacken' },
  { en: 'to receive', de: 'erhalten' },
  { en: 'to store', de: 'lagern' },
  { en: 'good', de: 'gut' },
  { en: 'bad', de: 'schlecht' },
  { en: 'big', de: 'groß' },
  { en: 'small', de: 'klein' },
  { en: 'easy', de: 'einfach' },
  { en: 'difficult', de: 'schwierig' },
  { en: 'fast', de: 'schnell' },
  { en: 'slow', de: 'langsam' },
  { en: 'busy', de: 'beschäftigt' },
  { en: 'available', de: 'verfügbar' },
  { en: 'correct', de: 'richtig' },
  { en: 'wrong', de: 'falsch' },
  { en: 'excuse me', de: 'Entschuldigen Sie' },
  { en: 'no problem', de: 'Kein Problem' },
  { en: 'nice to meet you', de: 'Schön, Sie kennenzulernen' },
  { en: 'have a nice day', de: 'Schönen Tag noch' },
];

const A2_WORDS: Omit<VocabEntry, 'id' | 'level'>[] = [
  { en: 'department', de: 'Abteilung' },
  { en: 'employee benefits', de: 'Mitarbeiterleistungen (Benefits)' },
  { en: 'workplace', de: 'Arbeitsplatz' },
  { en: 'responsibility', de: 'Verantwortung' },
  { en: 'experience', de: 'Erfahrung' },
  { en: 'skill', de: 'Fähigkeit' },
  { en: 'deadline', de: 'Frist / Deadline' },
  { en: 'priority', de: 'Priorität' },
  { en: 'permission', de: 'Erlaubnis' },
  { en: 'policy', de: 'Regel / Richtlinie' },
  { en: 'procedure', de: 'Vorgehen / Ablauf' },
  { en: 'strategy', de: 'Strategie' },
  { en: 'objective', de: 'Ziel (konkreter)' },
  { en: 'performance', de: 'Leistung / Performance' },
  { en: 'efficiency', de: 'Effizienz' },
  { en: 'issue', de: 'Problem / Thema' },
  { en: 'risk', de: 'Risiko' },
  { en: 'opportunity', de: 'Chance / Gelegenheit' },
  { en: 'improvement', de: 'Verbesserung' },
  { en: 'change (noun)', de: 'Änderung' },
  { en: 'update (noun)', de: 'Update / Aktualisierung' },
  { en: 'overview', de: 'Überblick' },
  { en: 'detail', de: 'Detail' },
  { en: 'background', de: 'Hintergrund' },
  { en: 'feedback (detailed)', de: 'ausführliches Feedback' },
  { en: 'confirmation', de: 'Bestätigung' },
  { en: 'request (formal)', de: 'Anfrage (formal)' },
  { en: 'reply (noun)', de: 'Antwort' },
  { en: 'follow-up', de: 'Nachfrage / Follow-up' },
  { en: 'reminder', de: 'Erinnerung' },
  { en: 'notice', de: 'Hinweis' },
  { en: 'announcement', de: 'Ankündigung' },
  { en: 'schedule (noun)', de: 'Zeitplan' },
  { en: 'arrangement', de: 'Organisation / Vereinbarung' },
  { en: 'agreement', de: 'Vereinbarung' },
  { en: 'terms', de: 'Bedingungen' },
  { en: 'condition', de: 'Bedingung' },
  { en: 'requirement', de: 'Anforderung' },
  { en: 'resource', de: 'Ressource' },
  { en: 'budget plan', de: 'Budgetplan' },
  { en: 'costs (plural)', de: 'Kosten' },
  { en: 'expense', de: 'Ausgabe / Aufwand' },
  { en: 'profit', de: 'Gewinn' },
  { en: 'loss', de: 'Verlust' },
  { en: 'revenue', de: 'Umsatz / Einnahmen' },
  { en: 'tax', de: 'Steuer' },
  { en: 'fee', de: 'Gebühr' },
  { en: 'refund', de: 'Rückerstattung' },
  { en: 'payment terms', de: 'Zahlungsbedingungen' },
  { en: 'receipt', de: 'Quittung' },
  { en: 'estimate', de: 'Schätzung / Kostenvoranschlag' },
  { en: 'to arrange', de: 'organisieren / vereinbaren' },
  { en: 'to postpone', de: 'verschieben' },
  { en: 'to reschedule', de: 'neu terminieren' },
  { en: 'to discuss', de: 'besprechen / diskutieren' },
  { en: 'to decide', de: 'entscheiden' },
  { en: 'to choose', de: 'auswählen' },
  { en: 'to suggest', de: 'vorschlagen' },
  { en: 'to recommend', de: 'empfehlen' },
  { en: 'to explain', de: 'erklären' },
  { en: 'to describe', de: 'beschreiben' },
  { en: 'to improve', de: 'verbessern' },
  { en: 'to increase', de: 'erhöhen / steigern' },
  { en: 'to decrease', de: 'senken / reduzieren' },
  { en: 'to reduce', de: 'reduzieren' },
  { en: 'to grow', de: 'wachsen' },
  { en: 'to reach', de: 'erreichen' },
  { en: 'to achieve', de: 'erreichen' },
  { en: 'to support', de: 'unterstützen' },
  { en: 'to provide', de: 'bereitstellen' },
  { en: 'to contact', de: 'kontaktieren' },
  { en: 'to respond', de: 'antworten / reagieren' },
  { en: 'to follow up', de: 'nachfassen' },
  { en: 'to remind', de: 'erinnern' },
  { en: 'to apologize', de: 'sich entschuldigen' },
  { en: 'to solve', de: 'lösen' },
  { en: 'to fix', de: 'reparieren / beheben' },
  { en: 'to deliver (on time)', de: 'pünktlich liefern' },
  { en: 'to negotiate', de: 'verhandeln' },
  { en: 'to offer', de: 'anbieten' },
  { en: 'to accept', de: 'akzeptieren' },
  { en: 'to refuse', de: 'ablehnen' },
  { en: 'to sign up', de: 'sich anmelden' },
  { en: 'to apply', de: 'sich bewerben' },
  { en: 'to interview', de: 'ein Vorstellungsgespräch führen' },
  { en: 'to train', de: 'schulen / trainieren' },
  { en: 'to manage', de: 'managen / leiten' },
  { en: 'to organize', de: 'organisieren' },
  { en: 'to prepare', de: 'vorbereiten' },
  { en: 'to complete', de: 'abschließen' },
  { en: 'to check in', de: 'einchecken / sich melden' },
  { en: 'regarding', de: 'bezüglich' },
  { en: 'according to', de: 'laut / gemäß' },
  { en: 'in addition', de: 'zusätzlich' },
  { en: 'however', de: 'jedoch' },
  { en: 'therefore', de: 'deshalb / daher' },
  { en: 'for example', de: 'zum Beispiel' },
  { en: 'as soon as possible', de: 'so schnell wie möglich' },
  { en: 'as discussed', de: 'wie besprochen' },
  { en: 'please find attached', de: 'anbei finden Sie' },
  { en: 'I would like to', de: 'ich möchte' },
  { en: 'could you please', de: 'könnten Sie bitte' },
  { en: 'I am available', de: 'ich bin verfügbar' },
  { en: 'let me know', de: 'geben Sie mir Bescheid' },
  { en: 'promotion', de: 'Promotion / Verkaufsaktion' },
  { en: 'advertising', de: 'Werbung' },
  { en: 'customer satisfaction', de: 'Kundenzufriedenheit' },
  { en: 'competition', de: 'Wettbewerb' },
  { en: 'competitor', de: 'Wettbewerber' },
  { en: 'trend', de: 'Trend' },
  { en: 'demand', de: 'Nachfrage' },
  { en: 'supply', de: 'Angebot (Markt)' },
  { en: 'price range', de: 'Preisspanne' },
  { en: 'market research', de: 'Marktforschung' },
  { en: 'survey', de: 'Umfrage' },
  { en: 'brand awareness', de: 'Markenbekanntheit' },
  { en: 'customer journey', de: 'Kundenreise' },
  { en: 'channel', de: 'Kanal' },
  { en: 'online', de: 'online' },
  { en: 'offline', de: 'offline' },
  { en: 'newsletter', de: 'Newsletter' },
  { en: 'content', de: 'Inhalt / Content' },
  { en: 'rating', de: 'Bewertung' },
  { en: 'review', de: 'Rezension / Bewertung' },
  { en: 'campaign result', de: 'Kampagnenergebnis' },
  { en: 'sales target', de: 'Vertriebsziel' },
  { en: 'quota', de: 'Quote / Zielvorgabe' },
  { en: 'pipeline', de: 'Sales-Pipeline' },
  { en: 'prospect', de: 'Interessent(in)' },
  { en: 'proposal', de: 'Vorschlag / Angebot (Inhalt)' },
  { en: 'contract terms', de: 'Vertragsbedingungen' },
  { en: 'delivery time', de: 'Lieferzeit' },
  { en: 'payment method', de: 'Zahlungsmethode' },
  { en: 'after-sales service', de: 'After-Sales-Service' },
  { en: 'customer retention', de: 'Kundenbindung' },
  { en: 'to contact a customer', de: 'einen Kunden kontaktieren' },
  { en: 'to close a deal', de: 'einen Deal abschließen' },
  { en: 'job description', de: 'Stellenbeschreibung' },
  { en: 'responsibilities', de: 'Aufgaben / Verantwortlichkeiten' },
  { en: 'qualification', de: 'Qualifikation' },
  { en: 'work experience', de: 'Berufserfahrung' },
  { en: 'reference', de: 'Referenz' },
  { en: 'contract type', de: 'Vertragsart' },
  { en: 'probation period', de: 'Probezeit' },
  { en: 'overtime', de: 'Überstunden' },
  { en: 'pay rise', de: 'Gehaltserhöhung' },
  { en: 'promotion (job)', de: 'Beförderung' },
  { en: 'teamwork', de: 'Teamarbeit' },
  { en: 'training session', de: 'Schulung / Trainingseinheit' },
  { en: 'work-life balance', de: 'Work-Life-Balance' },
  { en: 'to request leave', de: 'Urlaub beantragen' },
  { en: 'shipment', de: 'Sendung' },
  { en: 'tracking number', de: 'Sendungsnummer / Tracking-Nummer' },
  { en: 'delay', de: 'Verzögerung' },
  { en: 'damaged', de: 'beschädigt' },
  { en: 'replacement', de: 'Ersatz' },
  { en: 'inventory', de: 'Inventar / Bestand' },
  { en: 'stock level', de: 'Lagerbestand (Level)' },
  { en: 'order status', de: 'Bestellstatus' },
  { en: 'back order', de: 'Rückstand / Nachlieferung' },
  { en: 'supplier contact', de: 'Lieferantenkontakt' },
  { en: 'quality check', de: 'Qualitätsprüfung' },
  { en: 'analysis', de: 'Analyse' },
  { en: 'summary (short)', de: 'Kurz-Zusammenfassung' },
  { en: 'key finding', de: 'Kernaussage' },
  { en: 'recommendation (key)', de: 'Empfehlung' },
  { en: 'action plan', de: 'Maßnahmenplan' },
  { en: 'deadline (report)', de: 'Frist' },
  { en: 'next steps', de: 'nächste Schritte' },
  { en: 'figure', de: 'Kennzahl / Abbildung' },
  { en: 'percentage', de: 'Prozent' },
  { en: 'comparison', de: 'Vergleich' },
  { en: 'increase (noun)', de: 'Anstieg' },
  { en: 'decrease (noun)', de: 'Rückgang' },
  { en: 'to summarize', de: 'zusammenfassen' },
  { en: 'to report', de: 'berichten' },
  { en: 'to present', de: 'präsentieren' },
  { en: 'successful', de: 'erfolgreich' },
  { en: 'unsuccessful', de: 'nicht erfolgreich' },
  { en: 'effective', de: 'wirksam / effektiv' },
  { en: 'efficient', de: 'effizient' },
  { en: 'reliable', de: 'zuverlässig' },
  { en: 'unreliable', de: 'unzuverlässig' },
  { en: 'possible', de: 'möglich' },
  { en: 'impossible', de: 'unmöglich' },
  { en: 'usually', de: 'normalerweise' },
  { en: 'sometimes', de: 'manchmal' },
  { en: 'often', de: 'oft' },
  { en: 'rarely', de: 'selten' },
  { en: 'already', de: 'schon' },
  { en: 'still', de: 'immer noch' },
  { en: 'maybe', de: 'vielleicht' },
  { en: 'probably', de: 'wahrscheinlich' },
];

const B1_WORDS: Omit<VocabEntry, 'id' | 'level'>[] = [
  { en: 'stakeholder', de: 'Stakeholder / Anspruchsgruppe' },
  { en: 'objective (business)', de: 'Unternehmensziel' },
  { en: 'KPI (key performance indicator)', de: 'KPI / Kennzahl' },
  { en: 'benchmark', de: 'Benchmark / Vergleichswert' },
  { en: 'best practice', de: 'Best Practice' },
  { en: 'workflow', de: 'Arbeitsablauf / Workflow' },
  { en: 'capacity', de: 'Kapazität' },
  { en: 'bottleneck', de: 'Engpass' },
  { en: 'compliance', de: 'Compliance / Regelkonformität' },
  { en: 'guideline', de: 'Leitlinie' },
  { en: 'regulation', de: 'Vorschrift / Regulierung' },
  { en: 'stakeholder meeting', de: 'Stakeholder-Meeting' },
  { en: 'minutes (detailed)', de: 'Sitzungsprotokoll (detailliert)' },
  { en: 'decision', de: 'Entscheidung' },
  { en: 'decision-making', de: 'Entscheidungsfindung' },
  { en: 'ownership', de: 'Verantwortung / Ownership' },
  { en: 'alignment', de: 'Abstimmung / Alignment' },
  { en: 'escalation', de: 'Eskalation' },
  { en: 'approval', de: 'Freigabe / Genehmigung' },
  { en: 'implementation', de: 'Umsetzung' },
  { en: 'rollout', de: 'Einführung / Rollout' },
  { en: 'standardization', de: 'Standardisierung' },
  { en: 'documentation', de: 'Dokumentation' },
  { en: 'process improvement', de: 'Prozessverbesserung' },
  { en: 'root cause', de: 'Ursache (Root Cause)' },
  { en: 'root cause analysis', de: 'Ursachenanalyse' },
  { en: 'incident', de: 'Vorfall / Incident' },
  { en: 'outage', de: 'Ausfall' },
  { en: 'maintenance', de: 'Wartung' },
  { en: 'supplier performance', de: 'Lieferantenleistung' },
  { en: 'service level', de: 'Servicelevel' },
  { en: 'SLA (service level agreement)', de: 'SLA' },
  { en: 'lead time', de: 'Durchlaufzeit / Lieferzeit' },
  { en: 'forecast (noun)', de: 'Prognose' },
  { en: 'demand forecast', de: 'Nachfrageprognose' },
  { en: 'capacity planning', de: 'Kapazitätsplanung' },
  { en: 'cash flow', de: 'Cashflow' },
  { en: 'break-even point', de: 'Break-even-Punkt' },
  { en: 'margin', de: 'Marge' },
  { en: 'gross margin', de: 'Bruttomarge' },
  { en: 'net profit', de: 'Nettogewinn' },
  { en: 'operating costs', de: 'Betriebskosten' },
  { en: 'fixed costs', de: 'Fixkosten' },
  { en: 'variable costs', de: 'variable Kosten' },
  { en: 'investment', de: 'Investition' },
  { en: 'return on investment (ROI)', de: 'Return on Investment (ROI)' },
  { en: 'invoice number', de: 'Rechnungsnummer' },
  { en: 'purchase order', de: 'Bestellung (PO)' },
  { en: 'purchase order number', de: 'Bestellnummer' },
  { en: 'credit note', de: 'Gutschrift' },
  { en: 'payment reminder', de: 'Zahlungserinnerung / Mahnung' },
  { en: 'overdue', de: 'überfällig' },
  { en: 'budget approval', de: 'Budgetfreigabe' },
  { en: 'financial year', de: 'Geschäftsjahr' },
  { en: 'inquiry', de: 'Anfrage' },
  { en: 'request for information (RFI)', de: 'Informationsanfrage (RFI)' },
  { en: 'complaint (formal)', de: 'Reklamation / formelle Beschwerde' },
  { en: 'complaints handling', de: 'Beschwerdemanagement' },
  { en: 'clarification', de: 'Klärung' },
  { en: 'statement', de: 'Stellungnahme' },
  { en: 'deadline extension', de: 'Fristverlängerung' },
  { en: 'attachment(s)', de: 'Anhänge' },
  { en: 'enclosed', de: 'beigefügt' },
  { en: 'cc (carbon copy)', de: 'CC' },
  { en: 'bcc (blind carbon copy)', de: 'BCC' },
  { en: 'recipient', de: 'Empfänger(in)' },
  { en: 'sender', de: 'Absender(in)' },
  { en: 'to escalate', de: 'eskalieren' },
  { en: 'to clarify', de: 'klären' },
  { en: 'to confirm (in writing)', de: 'schriftlich bestätigen' },
  { en: 'to approve', de: 'freigeben / genehmigen' },
  { en: 'to reject', de: 'ablehnen' },
  { en: 'to propose', de: 'vorschlagen' },
  { en: 'to request', de: 'anfordern / bitten' },
  { en: 'to handle', de: 'bearbeiten' },
  { en: 'to resolve', de: 'lösen / klären' },
  { en: 'to escalate an issue', de: 'ein Problem eskalieren' },
  { en: 'to keep someone informed', de: 'jemanden auf dem Laufenden halten' },
  { en: 'please be advised', de: 'bitte beachten Sie' },
  { en: 'I would appreciate it if', de: 'ich wäre dankbar, wenn' },
  { en: 'at your earliest convenience', de: 'bei nächster Gelegenheit' },
  { en: 'executive summary', de: 'Management Summary' },
  { en: 'scope', de: 'Umfang' },
  { en: 'assumption', de: 'Annahme' },
  { en: 'limitation', de: 'Einschränkung' },
  { en: 'method', de: 'Methode' },
  { en: 'findings', de: 'Erkenntnisse' },
  { en: 'insight', de: 'Einsicht / Insight' },
  { en: 'trend analysis', de: 'Trendanalyse' },
  { en: 'variance', de: 'Abweichung' },
  { en: 'variance analysis', de: 'Abweichungsanalyse' },
  { en: 'target vs actual', de: 'Soll-Ist-Vergleich' },
  { en: 'budget variance', de: 'Budgetabweichung' },
  { en: 'risk assessment', de: 'Risikobewertung' },
  { en: 'mitigation', de: 'Risikominderung' },
  { en: 'action item', de: 'To-do / Action Item' },
  { en: 'owner (task owner)', de: 'Verantwortliche Person' },
  { en: 'timeline', de: 'Zeitachse / Timeline' },
  { en: 'milestone', de: 'Meilenstein' },
  { en: 'deliverable', de: 'Lieferobjekt / Deliverable' },
  { en: 'status update', de: 'Status-Update' },
  { en: 'progress report', de: 'Fortschrittsbericht' },
  { en: 'summary of results', de: 'Ergebniszusammenfassung' },
  { en: 'positioning', de: 'Positionierung' },
  { en: 'value proposition', de: 'Wertversprechen' },
  { en: 'unique selling point (USP)', de: 'Alleinstellungsmerkmal (USP)' },
  { en: 'segmentation', de: 'Segmentierung' },
  { en: 'customer segment', de: 'Kundensegment' },
  { en: 'targeting', de: 'Targeting / Zielgruppenansprache' },
  { en: 'branding', de: 'Branding' },
  { en: 'brand image', de: 'Markenimage' },
  { en: 'brand loyalty', de: 'Markentreue' },
  { en: 'conversion', de: 'Conversion / Umwandlung' },
  { en: 'conversion rate', de: 'Conversion Rate' },
  { en: 'lead generation', de: 'Leadgenerierung' },
  { en: 'landing page', de: 'Landingpage' },
  { en: 'call to action (CTA)', de: 'Call-to-Action (CTA)' },
  { en: 'SEO (search engine optimization)', de: 'SEO' },
  { en: 'SEA (search engine advertising)', de: 'SEA' },
  { en: 'paid ads', de: 'bezahlte Werbung' },
  { en: 'organic reach', de: 'organische Reichweite' },
  { en: 'reach (marketing)', de: 'Reichweite' },
  { en: 'engagement', de: 'Engagement / Interaktion' },
  { en: 'engagement rate', de: 'Engagement Rate' },
  { en: 'brand guidelines', de: 'Markenrichtlinien' },
  { en: 'marketing mix', de: 'Marketing-Mix' },
  { en: 'pricing strategy', de: 'Preisstrategie' },
  { en: 'promotion strategy', de: 'Promotionsstrategie' },
  { en: 'distribution channel', de: 'Vertriebskanal' },
  { en: 'market share', de: 'Marktanteil' },
  { en: 'customer acquisition', de: 'Kundengewinnung' },
  { en: 'customer lifetime value (CLV)', de: 'Customer Lifetime Value (CLV)' },
  { en: 'cost per lead (CPL)', de: 'Cost per Lead (CPL)' },
  { en: 'cost per click (CPC)', de: 'Cost per Click (CPC)' },
  { en: 'A/B test', de: 'A/B-Test' },
  { en: 'sales funnel', de: 'Sales Funnel' },
  { en: 'qualification (sales)', de: 'Qualifizierung' },
  { en: 'value-based selling', de: 'wertbasierter Verkauf' },
  { en: 'needs analysis', de: 'Bedarfsanalyse' },
  { en: 'objection', de: 'Einwand' },
  { en: 'objection handling', de: 'Einwandbehandlung' },
  { en: 'negotiation', de: 'Verhandlung' },
  { en: 'pricing', de: 'Preisgestaltung' },
  { en: 'quote (sales)', de: 'Angebot' },
  { en: 'proposal (sales)', de: 'Angebot / Proposal' },
  { en: 'contract negotiation', de: 'Vertragsverhandlung' },
  { en: 'follow-up call', de: 'Nachfassanruf' },
  { en: 'lead qualification', de: 'Lead-Qualifizierung' },
  { en: 'account management', de: 'Kundenbetreuung (Account Management)' },
  { en: 'key account', de: 'Key Account' },
  { en: 'key account management', de: 'Key Account Management' },
  { en: 'upselling', de: 'Upselling' },
  { en: 'cross-selling', de: 'Cross-Selling' },
  { en: 'renewal', de: 'Verlängerung' },
  { en: 'churn', de: 'Kundenabwanderung' },
  { en: 'to qualify a lead', de: 'einen Lead qualifizieren' },
  { en: 'to present an offer', de: 'ein Angebot präsentieren' },
  { en: 'to negotiate terms', de: 'Bedingungen verhandeln' },
  { en: 'to close (a deal)', de: 'abschließen (Deal)' },
  { en: 'recruitment', de: 'Recruiting / Personalbeschaffung' },
  { en: 'onboarding', de: 'Einarbeitung / Onboarding' },
  { en: 'offboarding', de: 'Austritt / Offboarding' },
  { en: 'job posting', de: 'Stellenausschreibung' },
  { en: 'shortlist', de: 'Shortlist' },
  { en: 'screening', de: 'Vorauswahl / Screening' },
  { en: 'assessment', de: 'Beurteilung / Assessment' },
  { en: 'performance review', de: 'Mitarbeitergespräch / Leistungsbeurteilung' },
  { en: 'appraisal', de: 'Bewertung / Beurteilung' },
  { en: 'training plan', de: 'Schulungsplan' },
  { en: 'development', de: 'Entwicklung' },
  { en: 'career path', de: 'Karriereweg' },
  { en: 'retention', de: 'Mitarbeiterbindung' },
  { en: 'turnover (staff)', de: 'Fluktuation' },
  { en: 'workforce', de: 'Belegschaft' },
  { en: 'headcount', de: 'Mitarbeiterzahl' },
  { en: 'vacancy', de: 'offene Stelle' },
  { en: 'candidate', de: 'Kandidat(in)' },
  { en: 'contract renewal', de: 'Vertragsverlängerung' },
  { en: 'notice period', de: 'Kündigungsfrist' },
  { en: 'termination', de: 'Kündigung' },
  { en: 'to resign', de: 'kündigen (selbst)' },
  { en: 'to terminate', de: 'kündigen (durch Arbeitgeber)' },
  { en: 'to recruit', de: 'rekrutieren' },
  { en: 'to onboard', de: 'einführen / einarbeiten' },
  { en: 'project scope', de: 'Projektumfang' },
  { en: 'project plan', de: 'Projektplan' },
  { en: 'project timeline', de: 'Projektzeitplan' },
  { en: 'resource allocation', de: 'Ressourcenzuteilung' },
  { en: 'project risk', de: 'Projektrisiko' },
  { en: 'project status', de: 'Projektstatus' },
  { en: 'stakeholder alignment', de: 'Stakeholder-Abstimmung' },
  { en: 'project kickoff', de: 'Projekt-Kickoff' },
  { en: 'kickoff meeting', de: 'Kickoff-Meeting' },
  { en: 'to kick off', de: 'starten (Kickoff)' },
  { en: 'to update', de: 'aktualisieren' },
  { en: 'to monitor', de: 'überwachen' },
  { en: 'to track', de: 'nachverfolgen' },
  { en: 'to allocate', de: 'zuweisen' },
  { en: 'to prioritize', de: 'priorisieren' },
  { en: 'system', de: 'System' },
  { en: 'software', de: 'Software' },
  { en: 'tool', de: 'Tool / Werkzeug' },
  { en: 'access', de: 'Zugriff' },
  { en: 'user account', de: 'Benutzerkonto' },
  { en: 'password', de: 'Passwort' },
  { en: 'data protection', de: 'Datenschutz' },
  { en: 'GDPR', de: 'DSGVO' },
  { en: 'backup', de: 'Backup / Sicherung' },
  { en: 'bug', de: 'Fehler (Bug)' },
  { en: 'feature', de: 'Funktion / Feature' },
  { en: 'update (software)', de: 'Update (Software)' },
  { en: 'to log in', de: 'sich einloggen' },
  { en: 'to log out', de: 'sich ausloggen' },
  { en: 'to reset (a password)', de: 'zurücksetzen' },
  { en: 'cost-effective', de: 'kosteneffektiv' },
  { en: 'customer-focused', de: 'kundenorientiert' },
  { en: 'time-consuming', de: 'zeitaufwendig' },
  { en: 'high priority', de: 'hohe Priorität' },
  { en: 'low priority', de: 'niedrige Priorität' },
  { en: 'on schedule', de: 'im Zeitplan' },
  { en: 'behind schedule', de: 'hinter dem Zeitplan' },
  { en: 'in line with', de: 'im Einklang mit' },
  { en: 'to be responsible for', de: 'zuständig sein für' },
  { en: 'to be in charge of', de: 'verantwortlich sein für' },
];

const B2_WORDS: Omit<VocabEntry, 'id' | 'level'>[] = [
  { en: 'corporate strategy', de: 'Unternehmensstrategie' },
  { en: 'business model', de: 'Geschäftsmodell' },
  { en: 'strategic initiative', de: 'strategische Initiative' },
  { en: 'governance', de: 'Governance / Unternehmensführung' },
  { en: 'accountability', de: 'Rechenschaft / Verantwortlichkeit' },
  { en: 'decision framework', de: 'Entscheidungsrahmen' },
  { en: 'stakeholder management', de: 'Stakeholder-Management' },
  { en: 'change management', de: 'Change Management' },
  { en: 'organizational structure', de: 'Organisationsstruktur' },
  { en: 'cross-functional', de: 'funktionsübergreifend' },
  { en: 'alignment meeting', de: 'Alignment-Meeting' },
  { en: 'resource constraints', de: 'Ressourcenengpässe' },
  { en: 'trade-off', de: 'Abwägung / Trade-off' },
  { en: 'prioritization matrix', de: 'Priorisierungsmatrix' },
  { en: 'roadmap', de: 'Roadmap' },
  { en: 'go/no-go decision', de: 'Go/No-Go-Entscheidung' },
  { en: 'risk appetite', de: 'Risikobereitschaft' },
  { en: 'risk register', de: 'Risikoregister' },
  { en: 'contingency plan', de: 'Notfallplan' },
  { en: 'business continuity', de: 'Geschäftskontinuität' },
  { en: 'business case', de: 'Business Case' },
  { en: 'cost-benefit analysis', de: 'Kosten-Nutzen-Analyse' },
  { en: 'profitability', de: 'Rentabilität' },
  { en: 'liquidity', de: 'Liquidität' },
  { en: 'working capital', de: 'Working Capital' },
  { en: 'accounts receivable', de: 'Forderungen' },
  { en: 'accounts payable', de: 'Verbindlichkeiten' },
  { en: 'depreciation', de: 'Abschreibung' },
  { en: 'amortization', de: 'Amortisation' },
  { en: 'cash conversion cycle', de: 'Cash Conversion Cycle' },
  { en: 'forecasting', de: 'Forecasting / Prognoseerstellung' },
  { en: 'budgeting', de: 'Budgetierung' },
  { en: 'cost center', de: 'Kostenstelle' },
  { en: 'profit center', de: 'Profitcenter' },
  { en: 'overhead', de: 'Gemeinkosten' },
  { en: 'cost allocation', de: 'Kostenverrechnung' },
  { en: 'sensitivity analysis', de: 'Sensitivitätsanalyse' },
  { en: 'scenario analysis', de: 'Szenarioanalyse' },
  { en: 'audit', de: 'Audit / Prüfung' },
  { en: 'internal control', de: 'Internes Kontrollsystem' },
  { en: 'to revert (email)', de: 'zurückkommen (per E-Mail)' },
  { en: 'to address (an issue)', de: 'ein Thema adressieren' },
  { en: 'to align', de: 'abstimmen' },
  { en: 'to follow through', de: 'durchziehen / konsequent umsetzen' },
  { en: 'to provide an update', de: 'ein Update geben' },
  { en: 'to proceed', de: 'fortfahren' },
  { en: 'to finalize', de: 'finalisieren / abschließen' },
  { en: 'to outline', de: 'skizzieren' },
  { en: 'to highlight', de: 'hervorheben' },
  { en: 'to emphasize', de: 'betonen' },
  { en: 'to elaborate', de: 'ausführen' },
  { en: 'to confirm receipt', de: 'Eingang bestätigen' },
  { en: 'to acknowledge', de: 'bestätigen / zur Kenntnis nehmen' },
  { en: 'to accommodate', de: 'entgegenkommen / berücksichtigen' },
  { en: 'to coordinate', de: 'koordinieren' },
  { en: 'to facilitate', de: 'ermöglichen / erleichtern' },
  { en: 'to ensure', de: 'sicherstellen' },
  { en: 'to mitigate', de: 'mindern' },
  { en: 'to comply', de: 'einhalten' },
  { en: 'to adhere to', de: 'sich halten an' },
  { en: 'to escalate to', de: 'eskalieren an' },
  { en: 'for your reference', de: 'zu Ihrer Information' },
  { en: 'please note that', de: 'bitte beachten Sie, dass' },
  { en: 'with reference to', de: 'unter Bezugnahme auf' },
  { en: 'as per', de: 'gemäß' },
  { en: 'in the meantime', de: 'in der Zwischenzeit' },
  { en: 'should you have any questions', de: 'falls Sie Fragen haben' },
  { en: 'I look forward to hearing from you', de: 'ich freue mich auf Ihre Rückmeldung' },
  { en: 'thank you in advance', de: 'vielen Dank im Voraus' },
  { en: 'data-driven', de: 'datengetrieben' },
  { en: 'evidence', de: 'Beleg / Evidenz' },
  { en: 'methodology', de: 'Methodik' },
  { en: 'constraints', de: 'Einschränkungen / Restriktionen' },
  { en: 'implication', de: 'Auswirkung / Implikation' },
  { en: 'impact', de: 'Auswirkung / Impact' },
  { en: 'correlation', de: 'Korrelation' },
  { en: 'causation', de: 'Kausalität' },
  { en: 'baseline', de: 'Ausgangswert / Baseline' },
  { en: 'trendline', de: 'Trendlinie' },
  { en: 'forecast accuracy', de: 'Prognosegenauigkeit' },
  { en: 'key takeaway', de: 'Kernaussage / Takeaway' },
  { en: 'executive briefing', de: 'Kurzbriefing für Management' },
  { en: 'recommendation rationale', de: 'Begründung der Empfehlung' },
  { en: 'appendix', de: 'Anhang (Report)' },
  { en: 'reference (source)', de: 'Quelle / Referenz' },
  { en: 'to quantify', de: 'quantifizieren' },
  { en: 'to assess', de: 'bewerten' },
  { en: 'to evaluate', de: 'evaluieren' },
  { en: 'to interpret', de: 'interpretieren' },
  { en: 'to derive', de: 'ableiten' },
  { en: 'to validate', de: 'validieren' },
  { en: 'brand positioning', de: 'Markenpositionierung' },
  { en: 'brand equity', de: 'Markenwert (Brand Equity)' },
  { en: 'go-to-market strategy', de: 'Go-to-Market-Strategie' },
  { en: 'marketing automation', de: 'Marketing-Automatisierung' },
  { en: 'lead nurturing', de: 'Lead Nurturing' },
  { en: 'customer persona', de: 'Kundenpersona' },
  { en: 'omnichannel', de: 'Omnichannel' },
  { en: 'attribution', de: 'Attribution / Zuordnung' },
  { en: 'attribution model', de: 'Attributionsmodell' },
  { en: 'funnel optimization', de: 'Funnel-Optimierung' },
  { en: 'retargeting', de: 'Retargeting' },
  { en: 'lookalike audience', de: 'Lookalike-Zielgruppe' },
  { en: 'conversion optimization', de: 'Conversion-Optimierung' },
  { en: 'cost per acquisition (CPA)', de: 'Cost per Acquisition (CPA)' },
  { en: 'return on ad spend (ROAS)', de: 'Return on Ad Spend (ROAS)' },
  { en: 'market penetration', de: 'Marktdurchdringung' },
  { en: 'product-market fit', de: 'Product-Market-Fit' },
  { en: 'strategic account', de: 'strategischer Kunde' },
  { en: 'account plan', de: 'Account-Plan' },
  { en: 'pipeline coverage', de: 'Pipeline-Abdeckung' },
  { en: 'deal velocity', de: 'Deal-Geschwindigkeit' },
  { en: 'sales enablement', de: 'Sales Enablement' },
  { en: 'value-based pricing', de: 'wertbasierte Preisgestaltung' },
  { en: 'discount approval', de: 'Rabattfreigabe' },
  { en: 'procurement', de: 'Einkauf (Procurement)' },
  { en: 'tender', de: 'Ausschreibung' },
  { en: 'request for proposal (RFP)', de: 'Ausschreibung / RFP' },
  { en: 'request for quotation (RFQ)', de: 'Angebotsanfrage / RFQ' },
  { en: 'commercial terms', de: 'kaufmännische Bedingungen' },
  { en: 'contractual obligations', de: 'vertragliche Verpflichtungen' },
  { en: 'service commitment', de: 'Service-Zusagen' },
  { en: 'renewal rate', de: 'Renewal Rate' },
  { en: 'churn rate', de: 'Churn Rate' },
  { en: 'customer success', de: 'Customer Success' },
  { en: 'escalation path', de: 'Eskalationsweg' },
  { en: 'to leverage', de: 'nutzen / hebeln' },
  { en: 'to upsell', de: 'Upsell betreiben' },
  { en: 'to cross-sell', de: 'Cross-Sell betreiben' },
  { en: 'talent acquisition', de: 'Talent Acquisition' },
  { en: 'employer branding', de: 'Employer Branding' },
  { en: 'compensation', de: 'Vergütung' },
  { en: 'compensation package', de: 'Vergütungspaket' },
  { en: 'benefits package', de: 'Benefits-Paket' },
  { en: 'incentive', de: 'Anreiz / Incentive' },
  { en: 'variable pay', de: 'variable Vergütung' },
  { en: 'performance management', de: 'Performance Management' },
  { en: 'succession planning', de: 'Nachfolgeplanung' },
  { en: 'employee engagement', de: 'Mitarbeiterengagement' },
  { en: 'labor law', de: 'Arbeitsrecht' },
  { en: 'collective agreement', de: 'Tarifvertrag' },
  { en: 'grievance', de: 'Beschwerde (intern)' },
  { en: 'to retain', de: 'halten / binden' },
  { en: 'to develop (employees)', de: 'weiterentwickeln' },
  { en: 'supply chain', de: 'Lieferkette' },
  { en: 'supply chain disruption', de: 'Störung der Lieferkette' },
  { en: 'supplier onboarding', de: 'Lieferanten-Onboarding' },
  { en: 'supplier evaluation', de: 'Lieferantenbewertung' },
  { en: 'quality assurance (QA)', de: 'Qualitätssicherung (QA)' },
  { en: 'continuous improvement', de: 'kontinuierliche Verbesserung' },
  { en: 'lean process', de: 'Lean-Prozess' },
  { en: 'inventory turnover', de: 'Lagerumschlag' },
  { en: 'safety stock', de: 'Sicherheitsbestand' },
  { en: 'freight', de: 'Fracht' },
  { en: 'customs', de: 'Zoll' },
  { en: 'incident management', de: 'Incident Management' },
  { en: 'information security', de: 'Informationssicherheit' },
  { en: 'access control', de: 'Zugriffskontrolle' },
  { en: 'role-based access', de: 'rollenbasierter Zugriff' },
  { en: 'data breach', de: 'Datenleck' },
  { en: 'encryption', de: 'Verschlüsselung' },
  { en: 'vulnerability', de: 'Schwachstelle' },
  { en: 'patch', de: 'Patch' },
  { en: 'system integration', de: 'Systemintegration' },
  { en: 'API', de: 'API' },
  { en: 'data quality', de: 'Datenqualität' },
  { en: 'data governance', de: 'Data Governance' },
  { en: 'significant', de: 'signifikant / erheblich' },
  { en: 'substantial', de: 'substanziell / erheblich' },
  { en: 'negligible', de: 'vernachlässigbar' },
  { en: 'consistent', de: 'konsistent' },
  { en: 'inconsistent', de: 'inkonsistent' },
  { en: 'transparent', de: 'transparent' },
  { en: 'robust', de: 'robust' },
  { en: 'scalable', de: 'skalierbar' },
  { en: 'sustainable', de: 'nachhaltig' },
  { en: 'accurate', de: 'genau' },
  { en: 'approximately', de: 'ungefähr' },
  { en: 'ultimately', de: 'letztendlich' },
  { en: 'notably', de: 'bemerkenswert' },
];

const C1_WORDS: Omit<VocabEntry, 'id' | 'level'>[] = [
  { en: 'strategic alignment', de: 'strategische Ausrichtung / Alignment' },
  { en: 'operating model', de: 'Betriebsmodell / Operating Model' },
  { en: 'organizational resilience', de: 'organisationale Resilienz' },
  { en: 'enterprise risk management (ERM)', de: 'Enterprise Risk Management (ERM)' },
  { en: 'risk mitigation plan', de: 'Plan zur Risikominderung' },
  { en: 'control environment', de: 'Kontrollumfeld' },
  { en: 'internal audit', de: 'Interne Revision' },
  { en: 'external audit', de: 'Externe Prüfung' },
  { en: 'regulatory scrutiny', de: 'aufsichtsrechtliche Prüfung / scrutiny' },
  { en: 'code of conduct', de: 'Verhaltenskodex' },
  { en: 'conflict of interest', de: 'Interessenkonflikt' },
  { en: 'whistleblowing', de: 'Whistleblowing / Hinweisgebersystem' },
  { en: 'board of directors', de: 'Vorstand / Board' },
  { en: 'shareholder value', de: 'Shareholder Value' },
  { en: 'corporate culture', de: 'Unternehmenskultur' },
  { en: 'organizational change', de: 'organisationaler Wandel' },
  { en: 'stakeholder engagement', de: 'Stakeholder-Einbindung' },
  { en: 'decision rationale', de: 'Entscheidungsbegründung' },
  { en: 'strategic roadmap', de: 'strategische Roadmap' },
  { en: 'portfolio management', de: 'Portfoliomanagement' },
  { en: 'resource optimization', de: 'Ressourcenoptimierung' },
  { en: 'operational excellence', de: 'Operational Excellence' },
  { en: 'value creation', de: 'Wertschöpfung / Wertgenerierung' },
  { en: 'value leakage', de: 'Wertverlust / Value Leakage' },
  { en: 'governance framework', de: 'Governance-Rahmenwerk' },
  { en: 'financial statement', de: 'Jahresabschluss / Finanzbericht' },
  { en: 'balance sheet', de: 'Bilanz' },
  { en: 'income statement', de: 'Gewinn- und Verlustrechnung' },
  { en: 'cash flow statement', de: 'Cashflow-Rechnung' },
  { en: 'P&L (profit and loss)', de: 'GuV (Profit and Loss)' },
  { en: 'cost of goods sold (COGS)', de: 'Herstellungskosten (COGS)' },
  { en: 'operating margin', de: 'operative Marge' },
  { en: 'EBITDA', de: 'EBITDA' },
  { en: 'capital expenditure (CapEx)', de: 'Investitionsausgaben (CapEx)' },
  { en: 'operational expenditure (OpEx)', de: 'Betriebsausgaben (OpEx)' },
  { en: 'run rate', de: 'Hochrechnung / Run Rate' },
  { en: 'burn rate', de: 'Kapitalverbrauch / Burn Rate' },
  { en: 'financial forecast', de: 'Finanzprognose' },
  { en: 'rolling forecast', de: 'Rolling Forecast' },
  { en: 'budget freeze', de: 'Budgetstopp' },
  { en: 'cost containment', de: 'Kostendämpfung' },
  { en: 'cost reduction program', de: 'Kostensenkungsprogramm' },
  { en: 'pricing power', de: 'Preissetzungsmacht' },
  { en: 'reconciliation', de: 'Abstimmung (z. B. Kontenabstimmung)' },
  { en: 'accrual', de: 'Abgrenzung (Accrual)' },
  { en: 'provision', de: 'Rückstellung' },
  { en: 'impairment', de: 'Wertminderung (Impairment)' },
  { en: 'write-off', de: 'Abschreibung / Ausbuchung' },
  { en: 'audit trail', de: 'Prüfpfad / Audit Trail' },
  { en: 'materiality', de: 'Wesentlichkeit' },
  { en: 'variance drivers', de: 'Treiber der Abweichung' },
  { en: 'granularity', de: 'Granularität' },
  { en: 'robustness', de: 'Robustheit' },
  { en: 'validity', de: 'Validität' },
  { en: 'reliability (measurement)', de: 'Reliabilität' },
  { en: 'confidence interval', de: 'Konfidenzintervall' },
  { en: 'statistical significance', de: 'statistische Signifikanz' },
  { en: 'sample size', de: 'Stichprobengröße' },
  { en: 'bias (data)', de: 'Verzerrung (Bias)' },
  { en: 'outlier', de: 'Ausreißer' },
  { en: 'data reconciliation', de: 'Datenabgleich' },
  { en: 'data lineage', de: 'Datenherkunft / Lineage' },
  { en: 'single source of truth (SSOT)', de: 'Single Source of Truth' },
  { en: 'data warehouse', de: 'Data Warehouse' },
  { en: 'dashboards', de: 'Dashboards' },
  { en: 'leading indicator', de: 'Frühindikator' },
  { en: 'lagging indicator', de: 'Spätindikator' },
  { en: 'sensitivity', de: 'Sensitivität' },
  { en: 'trade-off analysis', de: 'Trade-off-Analyse' },
  { en: 'scenario planning', de: 'Szenarioplanung' },
  { en: 'risk-adjusted', de: 'risikoadjustiert' },
  { en: 'evidence-based', de: 'evidenzbasiert' },
  { en: 'to substantiate', de: 'belegen / untermauern' },
  { en: 'to corroborate', de: 'bestätigen / stützen' },
  { en: 'to reconcile (data)', de: 'abgleichen' },
  { en: 'to triangulate', de: 'triangulieren (Daten/Infos)' },
  { en: 'to anticipate', de: 'vorwegnehmen / antizipieren' },
  { en: 'to benchmark', de: 'benchmarken / vergleichen' },
  { en: 'to calibrate', de: 'kalibrieren / abstimmen' },
  { en: 'to optimize', de: 'optimieren' },
  { en: 'to streamline', de: 'verschlanken' },
  { en: 'to leverage synergies', de: 'Synergien nutzen' },
  { en: 'to align stakeholders', de: 'Stakeholder abstimmen' },
  { en: 'to de-risk', de: 'Risiko reduzieren' },
  { en: 'market dynamics', de: 'Marktdynamik' },
  { en: 'competitive landscape', de: 'Wettbewerbsumfeld' },
  { en: 'differentiation', de: 'Differenzierung' },
  { en: 'brand architecture', de: 'Markenarchitektur' },
  { en: 'brand narrative', de: 'Markenstory / Narrative' },
  { en: 'thought leadership', de: 'Thought Leadership' },
  { en: 'product portfolio', de: 'Produktportfolio' },
  { en: 'product lifecycle', de: 'Produktlebenszyklus' },
  { en: 'product strategy', de: 'Produktstrategie' },
  { en: 'pricing architecture', de: 'Preisarchitektur' },
  { en: 'go-to-market motion', de: 'Go-to-Market-Ansatz' },
  { en: 'growth lever', de: 'Wachstumshebel' },
  { en: 'customer acquisition cost (CAC)', de: 'Customer Acquisition Cost (CAC)' },
  { en: 'unit economics', de: 'Unit Economics' },
  { en: 'net revenue retention (NRR)', de: 'Net Revenue Retention (NRR)' },
  { en: 'customer retention rate', de: 'Kundenbindungsrate' },
  { en: 'market expansion', de: 'Marktexpansion' },
  { en: 'category leadership', de: 'Kategorie-Führerschaft' },
  { en: 'brand consistency', de: 'Markenkonsistenz' },
  { en: 'content strategy', de: 'Content-Strategie' },
  { en: 'editorial calendar', de: 'Redaktionsplan' },
  { en: 'attribution window', de: 'Attributionsfenster' },
  { en: 'incrementality', de: 'Inkrementalität' },
  { en: 'lift (marketing)', de: 'Lift / Uplift' },
  { en: 'commercial negotiation', de: 'kaufmännische Verhandlung' },
  { en: 'procurement cycle', de: 'Beschaffungszyklus' },
  { en: 'total cost of ownership (TCO)', de: 'Total Cost of Ownership (TCO)' },
  { en: 'statement of work (SOW)', de: 'Leistungsbeschreibung (SOW)' },
  { en: 'master service agreement (MSA)', de: 'Rahmenvertrag (MSA)' },
  { en: 'terms and conditions (T&Cs)', de: 'Allgemeine Bedingungen (T&Cs)' },
  { en: 'liability', de: 'Haftung' },
  { en: 'indemnification', de: 'Freistellung / Schadloshaltung' },
  { en: 'warranty clause', de: 'Gewährleistungsklausel' },
  { en: 'termination clause', de: 'Kündigungsklausel' },
  { en: 'service credits', de: 'Servicegutschriften' },
  { en: 'discounting policy', de: 'Rabattpolitik' },
  { en: 'commercial concession', de: 'kaufmännisches Entgegenkommen' },
  { en: 'deal desk', de: 'Deal Desk' },
  { en: 'pipeline hygiene', de: 'Pipeline-Hygiene' },
  { en: 'forecast commit', de: 'Commit im Forecast' },
  { en: 'upsell motion', de: 'Upsell-Ansatz' },
  { en: 'renewal motion', de: 'Renewal-Ansatz' },
  { en: 'objection handling (advanced)', de: 'fortgeschrittene Einwandbehandlung' },
  { en: 'to concede', de: 'nachgeben / Zugeständnis machen' },
  { en: 'to counteroffer', de: 'Gegenangebot machen' },
  { en: 'to escalate commercially', de: 'kaufmännisch eskalieren' },
  { en: 'to close the gap', de: 'die Lücke schließen' },
  { en: 'talent management', de: 'Talentmanagement' },
  { en: 'learning and development (L&D)', de: 'Personalentwicklung (L&D)' },
  { en: 'performance calibration', de: 'Leistungskalibrierung' },
  { en: 'competency framework', de: 'Kompetenzmodell' },
  { en: 'succession pipeline', de: 'Nachfolge-Pipeline' },
  { en: 'employee value proposition (EVP)', de: 'Employer Value Proposition (EVP)' },
  { en: 'workforce planning', de: 'Personalbedarfsplanung' },
  { en: 'headcount planning', de: 'Headcount-Planung' },
  { en: 'compensation benchmarking', de: 'Vergütungsbenchmarking' },
  { en: 'job grading', de: 'Stellenbewertung / Job Grading' },
  { en: 'pay equity', de: 'Lohngerechtigkeit' },
  { en: 'collective bargaining', de: 'Tarifverhandlung' },
  { en: 'employee relations', de: 'Mitarbeiterbeziehungen' },
  { en: 'engagement survey', de: 'Mitarbeiterbefragung' },
  { en: 'attrition', de: 'Fluktuation / Attrition' },
  { en: 'retention driver', de: 'Treiber der Bindung' },
  { en: 'to mentor', de: 'mentoren / betreuen' },
  { en: 'to coach', de: 'coachen' },
  { en: 'to upskill', de: 'qualifizieren / upskillen' },
  { en: 'to reskill', de: 'umschulen / reskillen' },
  { en: 'end-to-end', de: 'End-to-End' },
  { en: 'operational bottleneck', de: 'operativer Engpass' },
  { en: 'capacity utilization', de: 'Kapazitätsauslastung' },
  { en: 'demand planning', de: 'Bedarfsplanung' },
  { en: 'inventory optimization', de: 'Bestandsoptimierung' },
  { en: 'supply planning', de: 'Lieferplanung' },
  { en: 'supplier lead time', de: 'Lieferanten-Lieferzeit' },
  { en: 'service level target', de: 'Servicelevel-Ziel' },
  { en: 'quality deviation', de: 'Qualitätsabweichung' },
  { en: 'corrective action', de: 'Korrekturmaßnahme' },
  { en: 'preventive action', de: 'Vorbeugemaßnahme' },
  { en: 'CAPA (corrective and preventive action)', de: 'CAPA' },
  { en: 'continuous delivery', de: 'Continuous Delivery' },
  { en: 'incident response', de: 'Incident Response' },
  { en: 'root cause remediation', de: 'Behebung der Ursache' },
  { en: 'enterprise architecture', de: 'Enterprise-Architektur' },
  { en: 'system landscape', de: 'Systemlandschaft' },
  { en: 'identity and access management (IAM)', de: 'Identity & Access Management (IAM)' },
  { en: 'security posture', de: 'Sicherheitslage' },
  { en: 'data governance operating model', de: 'Betriebsmodell für Data Governance' },
  { en: 'data stewardship', de: 'Datenverantwortung (Stewardship)' },
  { en: 'data access request', de: 'Antrag auf Datenzugriff' },
  { en: 'least privilege', de: 'Prinzip der geringsten Rechte' },
  { en: 'incident triage', de: 'Incident-Triage' },
  { en: 'post-mortem', de: 'Post-Mortem-Analyse' },
  { en: 'root cause fix', de: 'Fix der Root Cause' },
  { en: 'technical debt', de: 'technische Schulden' },
  { en: 'please refrain from', de: 'bitte sehen Sie davon ab' },
  { en: 'we would like to draw your attention to', de: 'wir möchten Ihre Aufmerksamkeit auf ... lenken' },
  { en: 'as a matter of urgency', de: 'dringend / mit höchster Dringlichkeit' },
  { en: 'pending your confirmation', de: 'vorbehaltlich Ihrer Bestätigung' },
  { en: 'to avoid any misunderstandings', de: 'um Missverständnisse zu vermeiden' },
  { en: 'for the sake of completeness', de: 'der Vollständigkeit halber' },
  { en: 'to the best of my knowledge', de: 'nach bestem Wissen' },
  { en: 'without prejudice', de: 'ohne Anerkennung einer Rechtspflicht' },
  { en: 'with immediate effect', de: 'mit sofortiger Wirkung' },
  { en: 'ambiguous', de: 'mehrdeutig' },
  { en: 'nuanced', de: 'nuanciert' },
  { en: 'comprehensive', de: 'umfassend' },
  { en: 'stringent', de: 'streng / stringent' },
  { en: 'pragmatic', de: 'pragmatisch' },
  { en: 'inherently', de: 'von Natur aus' },
  { en: 'predominantly', de: 'überwiegend' },
  { en: 'consequently', de: 'folglich' },
];

function buildLevel(level: CefrLevel, words: Omit<VocabEntry, 'id' | 'level'>[]): VocabEntry[] {
  return words.map((w, i) => ({ ...w, level, id: `${level.toLowerCase()}-${i + 1}` }));
}

export const VOCAB: VocabEntry[] = [
  ...buildLevel('A1', A1_WORDS),
  ...buildLevel('A2', A2_WORDS),
  ...buildLevel('B1', B1_WORDS),
  ...buildLevel('B2', B2_WORDS),
  ...buildLevel('C1', C1_WORDS),
];

export const CEFR_LEVELS: CefrLevel[] = ['A1', 'A2', 'B1', 'B2', 'C1'];

