import type { CaseStudy, DiagramDef, TermMatchSet } from './types';

// ============================================================
// STRATEGIE & FÜHRUNG — Übungsinhalte für den Üben-Modus.
// Jede Übung gehört zu einem Bereich (Führung/Strategie), einer von
// drei Schwierigkeitsstufen (anfaenger/fortgeschritten/profi) und
// deckt eines der Themenblöcke aus dem Lernen-Modus ab.
// ============================================================

const AMBER = '#E3A340';
const TEAL = '#4FB0A5';

export const DIAGRAMS: DiagramDef[] = [
  // ---------------------------------------------------------- FÜHRUNG
  {
    id: 'zweidimensionales-stilmodell',
    title: 'Das zweidimensionale Stil-Modell',
    subtitle: 'Führungsstile nach Aufgaben- und Beziehungsorientierung',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    intro:
      'Führungsstile lassen sich nach zwei Dimensionen einordnen: Beziehungsorientierung und Aufgabenorientierung. ' +
      'Ordne zuerst die beiden Achsen zu, danach die vier Grundstile.',
    columns: '64px 1fr 1fr',
    rows: '1fr 1fr 64px',
    areas: ['yaxis tl tr', 'yaxis bl br', '.     xaxis xaxis'],
    accent: AMBER,
    axisDistractors: ['Fachkompetenz'],
    slotDistractors: ['Kooperativer Stil'],
    axisTerms: [
      {
        id: 'stil-y',
        axis: 'y',
        label: 'Beziehungsorientierung',
        explanation: 'Beschreibt, wie stark die Führungskraft auf Nähe, Kommunikation und sozio-emotionale Unterstützung setzt.',
      },
      {
        id: 'stil-x',
        axis: 'x',
        label: 'Aufgabenorientierung',
        explanation: 'Beschreibt, wie stark die Führungskraft Aufgaben, Rollen und Ziele strukturiert und kontrolliert.',
      },
    ],
    slots: [
      {
        id: 'stil-integrierend',
        area: 'tl',
        label: 'Integrierender Stil',
        explanation: 'Niedrige Aufgaben-, hohe Beziehungsorientierung: Die Führungskraft kümmert sich stark um den Zusammenhalt, gibt aber wenig Struktur vor.',
      },
      {
        id: 'stil-partizipativ',
        area: 'tr',
        label: 'Partizipativer Stil',
        explanation: 'Hohe Aufgaben- UND hohe Beziehungsorientierung: Struktur und Zusammenhalt werden gleichermaßen betont.',
      },
      {
        id: 'stil-delegation',
        area: 'bl',
        label: 'Delegations-Stil',
        explanation: 'Niedrige Aufgaben- UND niedrige Beziehungsorientierung: Verantwortung wird weitgehend abgegeben, wenig Einmischung.',
      },
      {
        id: 'stil-autoritaer',
        area: 'br',
        label: 'Autoritärer Stil',
        explanation: 'Hohe Aufgaben-, niedrige Beziehungsorientierung: klare Vorgaben und Kontrolle stehen im Vordergrund, wenig Rücksicht auf die Beziehungsebene.',
      },
    ],
  },
  {
    id: 'reifegradmodell',
    title: 'Situatives Führungsmodell',
    subtitle: 'Reifegradmodell nach Hersey/Blanchard',
    area: 'fuehrung',
    difficulty: 'fortgeschritten',
    intro:
      'Nach Hersey/Blanchard ist der effektivste Führungsstil abhängig vom Reifegrad des Mitarbeiters bezüglich ' +
      'der Aufgabe. Ordne zuerst die beiden Orientierungs-Achsen zu, danach die vier Führungsstile in ihre Felder.',
    columns: '64px 1fr 1fr',
    rows: '1fr 1fr 64px',
    areas: ['yaxis tl tr', 'yaxis bl br', '.     xaxis xaxis'],
    accent: AMBER,
    axisDistractors: ['Fachkompetenz'],
    slotDistractors: ['Kooperativer Stil'],
    axisTerms: [
      {
        id: 'lead-y',
        axis: 'y',
        label: 'Beziehungsorientierung',
        explanation: 'Beziehungsorientierung beschreibt, in welchem Ausmaß die Führungskraft auf sozio-emotionale Unterstützung, Kommunikation und Zuhören setzt.',
      },
      {
        id: 'lead-x',
        axis: 'x',
        label: 'Aufgabenorientierung',
        explanation: 'Aufgabenorientierung beschreibt, in welchem Ausmaß die Führungskraft Aufgaben, Rollen und Ziele strukturiert, vorgibt und kontrolliert.',
      },
    ],
    slots: [
      {
        id: 'lead-participating',
        area: 'tl',
        label: 'Partizipativer Stil (S3)',
        explanation: 'Hohe Beziehungs-, geringe Aufgabenorientierung ("participating"). Passt zu Reifegrad M3 — der Mitarbeiter kann die Aufgabe, ist aber unsicher oder wenig motiviert.',
      },
      {
        id: 'lead-selling',
        area: 'tr',
        label: 'Integrierender Stil (S2)',
        explanation: 'Hohe Aufgaben- UND Beziehungsorientierung ("selling"). Passt zu Reifegrad M2 — der Mitarbeiter will, kann die Aufgabe aber noch nicht vollständig.',
      },
      {
        id: 'lead-delegating',
        area: 'bl',
        label: 'Delegierender Stil (S4)',
        explanation: 'Geringe Aufgaben- UND Beziehungsorientierung ("delegating"). Passt zu Reifegrad M4 — der Mitarbeiter kann und will.',
      },
      {
        id: 'lead-telling',
        area: 'br',
        label: 'Autoritärer Stil (S1)',
        explanation: 'Hohe Aufgaben-, geringe Beziehungsorientierung ("telling"). Passt zu Reifegrad M1 — der Mitarbeiter kann und will (noch) nicht.',
      },
    ],
  },
  {
    id: 'johari-fenster',
    title: 'Johari-Fenster',
    subtitle: 'Selbst- und Fremdbild als Grundlage für Feedback',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    intro:
      'Das Johari-Fenster zeigt, wie sich Selbst- und Fremdwahrnehmung überschneiden — die Basis für gutes ' +
      'Feedback in der Führungsarbeit. Ordne zuerst die beiden Achsen zu, danach die vier Felder.',
    columns: '64px 1fr 1fr',
    rows: '1fr 1fr 64px',
    areas: ['yaxis tl tr', 'yaxis bl br', '.     xaxis xaxis'],
    accent: AMBER,
    axisDistractors: ['Kompetenzniveau'],
    slotDistractors: ['Geheimnis'],
    axisTerms: [
      {
        id: 'johari-y',
        axis: 'y',
        label: 'Bekanntheit bei anderen',
        explanation: 'Beschreibt, ob eine Information über mich von anderen Menschen wahrgenommen wird oder nicht.',
      },
      {
        id: 'johari-x',
        axis: 'x',
        label: 'Bekanntheit bei mir selbst',
        explanation: 'Beschreibt, ob mir eine Information über mich selbst bewusst ist oder nicht.',
      },
    ],
    slots: [
      {
        id: 'johari-oeffentlich',
        area: 'tl',
        label: 'Freies Handeln',
        explanation: 'Mir bekannt UND anderen bekannt: Verhalten und Eigenschaften, die offen zutage liegen — die Basis für freie, unverkrampfte Zusammenarbeit.',
      },
      {
        id: 'johari-blind',
        area: 'tr',
        label: 'Blinder Fleck',
        explanation: 'Anderen bekannt, mir aber UNbekannt: Dinge, die andere an mir wahrnehmen, die mir selbst nicht bewusst sind — genau hier setzt ehrliches Feedback an.',
      },
      {
        id: 'johari-fassade',
        area: 'bl',
        label: 'Verborgenes',
        explanation: 'Mir bekannt, anderen aber UNbekannt: Dinge, die ich bewusst verberge oder nicht preisgebe.',
      },
      {
        id: 'johari-unbekannt',
        area: 'br',
        label: 'Unbekanntes',
        explanation: 'Weder mir noch anderen bekannt: unbewusstes Potenzial oder Verhalten, das erst durch neue Situationen sichtbar wird.',
      },
    ],
  },
  {
    id: 'eisbergmodell-diagramm',
    title: 'Das Eisbergmodell',
    subtitle: 'Sichtbare und unsichtbare Ebene der Kommunikation',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    intro:
      'Eine sichtbare Kommunikationsstörung ist nur die Spitze eines Eisbergs. Ordne die beiden Ebenen den ' +
      'richtigen Zonen zu.',
    columns: '1fr',
    rows: '1fr 1fr',
    areas: ['oben', 'unten'],
    accent: AMBER,
    slotDistractors: ['Mittlere Ebene'],
    axisTerms: [],
    slots: [
      {
        id: 'eisberg-sichtbar',
        area: 'oben',
        label: 'Sichtbare Ebene',
        explanation: 'Über der Wasserlinie: Themen, Ziele, Termine und Rollen — das, was in einem Gespräch offen ausgesprochen wird.',
      },
      {
        id: 'eisberg-unsichtbar',
        area: 'unten',
        label: 'Unsichtbare Ebene',
        explanation: 'Unter der Wasserlinie: Gefühle, Ängste, Werte, Erfahrungen und Konflikte — die eigentliche Ursache vieler Störungen.',
      },
    ],
  },
  {
    id: 'vier-seiten-modell',
    title: 'Vier-Seiten-einer-Nachricht',
    subtitle: 'Das Kommunikationsquadrat nach Schulz von Thun',
    area: 'fuehrung',
    difficulty: 'profi',
    intro:
      'Jede Nachricht hat vier Seiten, auf denen gesendet und empfangen wird. Ordne die vier Seiten rund um ' +
      'die Nachricht an.',
    columns: '1fr 1.3fr 1fr',
    rows: '1fr 1fr 1fr',
    areas: ['.    top    .', 'left center right', '.    bottom .'],
    accent: AMBER,
    fixedBoxes: [{ label: 'Nachricht', area: 'center' }],
    slotDistractors: ['Feedback', 'Ich-Botschaft'],
    axisTerms: [],
    slots: [
      { id: 'vs-sach', area: 'top', label: 'Sachinformation', explanation: 'Worüber der Sender informiert — der reine Sachinhalt der Nachricht.' },
      { id: 'vs-selbst', area: 'left', label: 'Selbstkundgabe', explanation: 'Was der Sender von sich selbst preisgibt, bewusst oder unbewusst.' },
      { id: 'vs-beziehung', area: 'right', label: 'Beziehungshinweis', explanation: 'Was der Sender vom Empfänger hält und wie er zu ihm steht.' },
      { id: 'vs-appell', area: 'bottom', label: 'Appell', explanation: 'Was der Sender beim Empfänger erreichen möchte.' },
    ],
  },
  {
    id: 'werte-entwicklungsquadrat',
    title: 'Werte- und Entwicklungsquadrat',
    subtitle: 'Konfliktbehandlung nach Schulz von Thun',
    area: 'fuehrung',
    difficulty: 'fortgeschritten',
    intro:
      'Jede positive Eigenschaft hat eine wertvolle "Schwestertugend" — wird sie ohne diese übertrieben, kippt ' +
      'sie ins Negative. Ordne die vier Begriffe den richtigen Feldern zu (oben = positiver Kern, unten = Übertreibung).',
    columns: '1fr 1fr',
    rows: '1fr 1fr',
    areas: ['wert kritik', 'schmeichel gering'],
    accent: AMBER,
    axisTerms: [],
    slotDistractors: ['Anpassung', 'Ignoranz'],
    slots: [
      {
        id: 'wq-wertschaetzung',
        area: 'wert',
        label: 'Wertschätzung',
        explanation: 'Positiver Kern: Anerkennung und Würdigung des anderen — die wertschätzende Schwestertugend zur offenen Kritik.',
      },
      {
        id: 'wq-kritik',
        area: 'kritik',
        label: 'Kritik',
        explanation: 'Positiver Kern: offene, ehrliche Konfrontation, die auf Verbesserung zielt — die kritische Schwestertugend zur Wertschätzung.',
      },
      {
        id: 'wq-schmeichelei',
        area: 'schmeichel',
        label: 'Schmeichelei',
        explanation: 'Übertreibung der Wertschätzung ohne Kritik: unkritische Anbiederung und Idealisierung ohne Ehrlichkeit.',
      },
      {
        id: 'wq-geringschaetzung',
        area: 'gering',
        label: 'Geringschätzung',
        explanation: 'Übertreibung der Kritik ohne Wertschätzung: Herabsetzung und Verachtung des anderen.',
      },
    ],
  },
  {
    id: 'goleman-vier-dimensionen',
    title: 'Emotionale Führung nach Goleman',
    subtitle: 'Vier Dimensionen emotionaler Intelligenz',
    area: 'fuehrung',
    difficulty: 'profi',
    intro:
      'Goleman & Boyatzis unterscheiden vier Dimensionen emotionaler Führung. Ordne die vier Begriffe den ' +
      'richtigen Feldern zu.',
    columns: '1fr 1fr',
    rows: '1fr 1fr',
    areas: ['selbstwahr sozial', 'selbstmanage beziehung'],
    accent: AMBER,
    slotDistractors: ['Zeitmanagement'],
    axisTerms: [],
    slots: [
      { id: 'gol-selbstwahr', area: 'selbstwahr', label: 'Selbstwahrnehmung', explanation: 'Ich + Erkennen: emotionale Selbstwahrnehmung, zutreffende Selbsteinschätzung, Selbstvertrauen.' },
      { id: 'gol-sozial', area: 'sozial', label: 'Soziales Bewusstsein', explanation: 'Andere + Erkennen: Empathie, Organisationsbewusstsein, Serviceorientierung.' },
      { id: 'gol-selbstmanage', area: 'selbstmanage', label: 'Selbstmanagement', explanation: 'Ich + Handeln: Selbstkontrolle, Transparenz, Optimismus, Anpassungsfähigkeit, Initiative.' },
      { id: 'gol-beziehung', area: 'beziehung', label: 'Beziehungsmanagement', explanation: 'Andere + Handeln: Entwicklung fördern, inspirierende Führung, Konfliktmanagement, Teamwork.' },
    ],
  },
  {
    id: 'kraftfeld-lewin',
    title: 'Kraftfeld-Ansatz nach Lewin',
    subtitle: 'Drei Phasen des geplanten Wandels',
    area: 'fuehrung',
    difficulty: 'fortgeschritten',
    intro:
      'Lewins Gleichgewichtsmodell beschreibt drei Phasen des Wandels. Ordne die drei Phasen in ihrer ' +
      'richtigen Reihenfolge zu.',
    columns: '1fr 1fr 1fr',
    rows: '1fr',
    areas: ['unfreeze change refreeze'],
    accent: AMBER,
    slotDistractors: ['Stabilisierung'],
    axisTerms: [],
    slots: [
      { id: 'lewin-unfreeze', area: 'unfreeze', label: 'Unfreezing', explanation: 'Auftauen: das bestehende Gleichgewicht wird aufgebrochen, Veränderungsbereitschaft wird geschaffen.' },
      { id: 'lewin-change', area: 'change', label: 'Changing', explanation: 'Verändern: neue Verhaltensweisen und Strukturen werden erprobt und eingeführt.' },
      { id: 'lewin-refreeze', area: 'refreeze', label: 'Refreezing', explanation: 'Wieder-Einfrieren: der neue Zustand wird stabilisiert und dauerhaft verankert.' },
    ],
  },

  // ---------------------------------------------------------- STRATEGIE
  {
    id: 'five-forces',
    title: 'Porters Five Forces',
    subtitle: 'Branchenstrukturanalyse nach Michael Porter',
    area: 'strategie',
    difficulty: 'anfaenger',
    intro:
      'Das Five-Forces-Modell analysiert fünf Wettbewerbskräfte, die gemeinsam die Attraktivität einer Branche ' +
      'bestimmen. Der Branchenwettbewerb steht im Zentrum — ziehe die vier weiteren Kräfte an ihre Position rund um ihn herum.',
    columns: '1fr 1.3fr 1fr',
    rows: '1fr 1fr 1fr',
    areas: ['.    top    .', 'left center right', '.    bottom .'],
    accent: TEAL,
    axisTerms: [],
    fixedBoxes: [{ label: 'Branchen­wettbewerber', area: 'center' }],
    slots: [
      {
        id: 'ff-new',
        area: 'top',
        label: 'Neue Wettbewerber',
        explanation: 'Die Gefahr des Markteintritts neuer Wettbewerber hängt von den Markteintrittsbarrieren ab, z. B. Economies of Scale, Produktdifferenzierung, Kapitalbedarf und regulatorische Eingriffe des Staates.',
      },
      {
        id: 'ff-suppliers',
        area: 'left',
        label: 'Lieferanten',
        explanation: 'Die Verhandlungsmacht der Lieferanten ist umso größer, je konzentrierter und organisierter sie auftreten und je weniger Substitutionsmöglichkeiten es für ihren Einsatzstoff gibt.',
      },
      {
        id: 'ff-customers',
        area: 'right',
        label: 'Kunden',
        explanation: 'Die Verhandlungsmacht (Käufermacht) der Kunden ist umso größer, je konzentrierter und organisierter die Abnehmer sind und je geringer die Wechselkosten für sie sind.',
      },
      {
        id: 'ff-substitutes',
        area: 'bottom',
        label: 'Substitutionsprodukte',
        explanation: 'Je geringer die Wechselkosten und je höher die wahrgenommene Gleichwertigkeit des Ersatzprodukts, desto größer die Gefahr sinkender Preise und Gewinne.',
      },
    ],
  },
  {
    id: 'swot-diagramm',
    title: 'Die SWOT-Matrix',
    subtitle: 'Interne und externe Analyse im Überblick',
    area: 'strategie',
    difficulty: 'anfaenger',
    intro:
      'Die SWOT-Analyse kombiniert eine interne und externe Perspektive. Ordne zuerst die beiden Achsen, ' +
      'danach die vier Felder zu.',
    columns: '64px 1fr 1fr',
    rows: '1fr 1fr 64px',
    areas: ['yaxis tl tr', 'yaxis bl br', '.     xaxis xaxis'],
    accent: TEAL,
    axisDistractors: ['Kernkompetenzen'],
    slotDistractors: ['Marktanteile'],
    axisTerms: [
      {
        id: 'swot-y',
        axis: 'y',
        label: 'Herkunft: intern (oben) / extern (unten)',
        explanation: 'Beschreibt, ob eine Beobachtung aus dem Unternehmen selbst stammt oder aus dessen Marktumfeld.',
      },
      {
        id: 'swot-x',
        axis: 'x',
        label: 'Wirkung: positiv (links) / negativ (rechts)',
        explanation: 'Beschreibt, ob eine Beobachtung positiv oder negativ für das Unternehmen ist.',
      },
    ],
    slots: [
      { id: 'swot-staerken', area: 'tl', label: 'Stärken', explanation: 'Intern + positiv: eigene Ressourcen und Fähigkeiten, die dem Unternehmen einen Vorteil verschaffen.' },
      { id: 'swot-schwaechen', area: 'tr', label: 'Schwächen', explanation: 'Intern + negativ: eigene Defizite, die das Unternehmen selbst beheben muss.' },
      { id: 'swot-chancen', area: 'bl', label: 'Chancen', explanation: 'Extern + positiv: Entwicklungen im Marktumfeld, die das Unternehmen nutzen kann.' },
      { id: 'swot-risiken', area: 'br', label: 'Risiken', explanation: 'Extern + negativ: Entwicklungen im Marktumfeld, die das Unternehmen bedrohen.' },
    ],
  },
  {
    id: 'bcg-matrix',
    title: 'BCG-Matrix',
    subtitle: 'Portfolio-Analyse nach der Boston Consulting Group',
    area: 'strategie',
    difficulty: 'fortgeschritten',
    intro:
      'Die BCG-Matrix ordnet Geschäftsfelder oder Produkte anhand von zwei Kennzahlen ein, um Investitions- ' +
      'entscheidungen im Portfolio zu treffen. Ziehe zuerst die beiden Achsenbegriffe an die richtige Stelle, ' +
      'danach die vier Feldnamen in die passenden Quadranten.',
    columns: '64px 1fr 1fr',
    rows: '1fr 1fr 64px',
    areas: ['yaxis tl tr', 'yaxis bl br', '.     xaxis xaxis'],
    accent: TEAL,
    axisTerms: [
      {
        id: 'bcg-y',
        axis: 'y',
        label: 'Marktwachstum',
        explanation: 'Das Marktwachstum ist ein Indikator für die Attraktivität eines Marktsegments. Hohes Wachstum erfordert meist hohe Investitionen.',
      },
      {
        id: 'bcg-x',
        axis: 'x',
        label: 'Relativer Marktanteil',
        explanation: 'Der relative Marktanteil setzt den eigenen Marktanteil ins Verhältnis zum stärksten Wettbewerber und gilt als Indikator für die Wettbewerbsposition.',
      },
    ],
    slots: [
      {
        id: 'bcg-stars',
        area: 'tl',
        label: 'Stars',
        explanation: 'Hohes Marktwachstum bei hohem relativem Marktanteil. Hoher Investitionsbedarf, aber auch hohe Erträge.',
      },
      {
        id: 'bcg-questionmarks',
        area: 'tr',
        label: 'Question Marks',
        explanation: 'Hohes Marktwachstum, aber (noch) geringer Marktanteil. Hoher Kapitalbedarf bei unsicherem Ertrag.',
      },
      {
        id: 'bcg-cashcows',
        area: 'bl',
        label: 'Cash Cows',
        explanation: 'Niedriges Marktwachstum, aber hoher Marktanteil. Geringer Investitionsbedarf bei hohen und stabilen Cashflows.',
      },
      {
        id: 'bcg-poordogs',
        area: 'br',
        label: 'Poor Dogs',
        explanation: 'Niedriges Marktwachstum und niedriger Marktanteil. Geringe strategische Bedeutung.',
      },
    ],
  },
  {
    id: 'wertschoepfungskette',
    title: 'Die Wertschöpfungskette',
    subtitle: 'Primäre Aktivitäten nach Porter',
    area: 'strategie',
    difficulty: 'fortgeschritten',
    intro:
      'Die Wertschöpfungskette gliedert die primären Aktivitäten eines Unternehmens vom Wareneingang bis zum ' +
      'Service. Ordne die fünf primären Aktivitäten in der richtigen Reihenfolge zu.',
    columns: '1fr 1fr 1fr 1fr 1fr',
    rows: '1fr 46px',
    areas: ['ein prod aus mkt serv', 'sek sek sek sek sek'],
    accent: TEAL,
    fixedBoxes: [{ label: 'Sekundäre Aktivitäten: General Management, Personal, Technologie, Beschaffung', area: 'sek' }],
    slotDistractors: ['Controlling'],
    axisTerms: [],
    slots: [
      { id: 'wsk-eingang', area: 'ein', label: 'Eingangslogistik', explanation: 'Eingang, Kontrolle, Lagerung und Weitertransport der Einsatzmengen (Rohstoffe, Vorprodukte).' },
      { id: 'wsk-produktion', area: 'prod', label: 'Produktion', explanation: 'Die wertsteigernde Transformation der Einsatzstoffe, inkl. Qualitätsprüfung und Wartung.' },
      { id: 'wsk-ausgang', area: 'aus', label: 'Ausgangslogistik', explanation: 'Lagerung und Distribution der fertigen Leistung an die Kunden.' },
      { id: 'wsk-marketing', area: 'mkt', label: 'Marketing & Vertrieb', explanation: 'Alle verkaufsgerichteten Aktivitäten, mit denen Kunden zum Kauf bewegt werden.' },
      { id: 'wsk-service', area: 'serv', label: 'Service', explanation: 'Kundenbetreuung und Ersatzteillieferung nach dem Verkauf.' },
    ],
  },
  {
    id: 'generische-strategien',
    title: 'Die drei generischen Strategien',
    subtitle: 'Wettbewerbsstrategien nach Michael Porter',
    area: 'strategie',
    difficulty: 'profi',
    intro:
      'Porter unterscheidet Geschäftsstrategien nach strategischer Ausrichtung (Gesamt- oder Teilmarkt) und ' +
      'strategischem Vorteil (Einzigartigkeit oder Kostenminimum). Ordne zuerst die Achsen, dann die drei Strategien zu.',
    columns: '64px 1fr 1fr',
    rows: '1fr 1fr 64px',
    areas: ['yaxis diff kf', 'yaxis konz konz', '.     xaxis xaxis'],
    accent: TEAL,
    axisDistractors: ['Kundenzufriedenheit'],
    slotDistractors: ['Diversifikation'],
    axisTerms: [
      {
        id: 'gs-y',
        axis: 'y',
        label: 'Strategische Ausrichtung',
        explanation: 'Werden die Güter/Dienstleistungen auf dem gesamten Branchenmarkt angeboten (Gesamtmarkt) oder nur auf einem Teilmarkt (Nische)?',
      },
      {
        id: 'gs-x',
        axis: 'x',
        label: 'Strategischer Vorteil',
        explanation: 'Basiert der Wettbewerbsvorteil auf vom Kunden wahrgenommener Einzigartigkeit oder auf dem geringsten Preis (Kostenminimum)?',
      },
    ],
    slots: [
      {
        id: 'gs-differenzierung',
        area: 'diff',
        label: 'Differenzierung',
        explanation: 'Gesamtmarkt + Einzigartigkeit: Das Angebot wird vom Kunden als einzigartig wahrgenommen (z. B. Markenimage, Produktdesign).',
      },
      {
        id: 'gs-kostenfuehrerschaft',
        area: 'kf',
        label: 'Kostenführerschaft',
        explanation: 'Gesamtmarkt + Kostenminimum: ein vergleichbares Produkt zum niedrigsten Preis der Branche, ermöglicht durch Economies of Scale.',
      },
      {
        id: 'gs-konzentration',
        area: 'konz',
        label: 'Konzentration (Fokussierung)',
        explanation: 'Teilmarkt: Beschränkung auf ein Nischensegment, in dem dann entweder differenziert oder kostenführend agiert wird.',
      },
    ],
  },
  {
    id: 'ansoff-matrix',
    title: 'Ansoff-Matrix',
    subtitle: 'Produkt-Markt-Strategien nach Igor Ansoff',
    area: 'strategie',
    difficulty: 'profi',
    intro:
      'Die Ansoff-Matrix zeigt vier Wachstumsstrategien, je nachdem ob ein Unternehmen bestehende oder neue ' +
      'Produkte auf bestehenden oder neuen Märkten anbietet. Ziehe zuerst die beiden Achsen zu, danach die vier Strategien.',
    columns: '64px 1fr 1fr',
    rows: '1fr 1fr 64px',
    areas: ['yaxis tl tr', 'yaxis bl br', '.     xaxis xaxis'],
    accent: TEAL,
    axisTerms: [
      {
        id: 'ansoff-y',
        axis: 'y',
        label: 'Markt (bestehend/neu)',
        explanation: 'Wird der bereits bekannte Markt bedient, oder wird ein neuer Markt erschlossen (z. B. neue Region, neue Zielgruppe)?',
      },
      {
        id: 'ansoff-x',
        axis: 'x',
        label: 'Produkt (bestehend/neu)',
        explanation: 'Wird ein bereits vorhandenes Produkt weiterverwendet, oder wird ein neues Produkt entwickelt?',
      },
    ],
    slots: [
      {
        id: 'ansoff-marktdurchdringung',
        area: 'tl',
        label: 'Marktdurchdringung',
        explanation: 'Bestehender Markt + bestehendes Produkt: Vorhandene Produkte auf bestehenden Märkten intensiver vermarkten — die risikoärmste Wachstumsstrategie.',
      },
      {
        id: 'ansoff-produktentwicklung',
        area: 'tr',
        label: 'Produktentwicklung',
        explanation: 'Bestehender Markt + neues Produkt: neue Produkte für bereits bekannte Märkte und Kunden entwickeln.',
      },
      {
        id: 'ansoff-marktentwicklung',
        area: 'bl',
        label: 'Marktentwicklung',
        explanation: 'Neuer Markt + bestehendes Produkt: bestehende Produkte auf neuen Märkten anbieten, z. B. in neuen Regionen.',
      },
      {
        id: 'ansoff-diversifikation',
        area: 'br',
        label: 'Diversifikation',
        explanation: 'Neuer Markt + neues Produkt: die risikoreichste Strategie — oft durch Zukauf oder Kooperation umgesetzt.',
      },
    ],
  },
];

export const CASE_STUDIES: CaseStudy[] = [
  // ---------------------------------------------------------- FÜHRUNG
  {
    id: 'lokomotion-kohaesion',
    title: 'Die zwei Funktionen der Führung',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    scenario: 'Eine Teamleiterin zeigt in ihrem Führungsalltag ganz unterschiedliche Verhaltensweisen.',
    instructions: 'Ordne jedes Verhalten der passenden Führungsfunktion zu.',
    columns: '1fr 1fr',
    rows: '1fr',
    areas: ['loko koha'],
    accent: AMBER,
    quadrants: [
      { id: 'loko', area: 'loko', title: 'Lokomotionsfunktion', hint: 'Aufgabenerfüllung & Zielerreichung' },
      { id: 'koha', area: 'koha', title: 'Kohäsionsfunktion', hint: 'Zusammenhalt & Integration' },
    ],
    items: [
      { id: 'l1', label: 'Sie legt für das Quartal klare Verkaufsziele je Mitarbeiter fest.', correctQuadrant: 'loko', explanation: 'Zielvorgaben dienen direkt der Aufgabenerfüllung der Gruppe.' },
      { id: 'l2', label: 'Sie kontrolliert wöchentlich den Fortschritt der einzelnen Projektschritte.', correctQuadrant: 'loko', explanation: 'Fortschrittskontrolle fördert die Zielerreichung der Gruppe.' },
      { id: 'l3', label: 'Sie organisiert ein Teamfrühstück, damit sich neue Kollegen besser kennenlernen.', correctQuadrant: 'koha', explanation: 'Fördert den Zusammenhalt und ein förderliches Arbeitsklima.' },
      { id: 'l4', label: 'Sie vermittelt in einem Streit zwischen zwei Teammitgliedern.', correctQuadrant: 'koha', explanation: 'Integration und Konfliktlösung stärken den Zusammenhalt der Gruppe.' },
      { id: 'l5', label: 'Sie verteilt die Aufgaben eines neuen Projekts nach Kompetenzen im Team.', correctQuadrant: 'loko', explanation: 'Aufgabenverteilung dient direkt der Zielerreichung.' },
      { id: 'l6', label: 'Sie sorgt dafür, dass auch stille Teammitglieder in Meetings zu Wort kommen.', correctQuadrant: 'koha', explanation: 'Fördert Integration und ein Klima, in dem sich alle einbringen können.' },
    ],
  },
  {
    id: 'herzberg-hygiene-motivatoren',
    title: 'Herzbergs Zwei-Faktoren-Theorie',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    scenario: 'Ein Unternehmen überlegt, mit welchen Maßnahmen es die Zufriedenheit seiner Mitarbeitenden verbessern kann.',
    instructions: 'Ordne jede Maßnahme der passenden Kategorie nach Herzberg zu.',
    columns: '1fr 1fr',
    rows: '1fr',
    areas: ['hygiene motivator'],
    accent: AMBER,
    quadrants: [
      { id: 'hygiene', area: 'hygiene', title: 'Hygienefaktor', hint: 'verhindert Unzufriedenheit' },
      { id: 'motivator', area: 'motivator', title: 'Motivator', hint: 'schafft echte Zufriedenheit' },
    ],
    items: [
      { id: 'h1', label: 'Gehaltserhöhung um 5 %', correctQuadrant: 'hygiene', explanation: 'Gehalt ist ein klassischer Hygienefaktor — verhindert Unzufriedenheit, motiviert aber nicht dauerhaft.' },
      { id: 'h2', label: 'Neue, ergonomische Bürostühle für alle', correctQuadrant: 'hygiene', explanation: 'Arbeitsbedingungen zählen zu den Hygienefaktoren.' },
      { id: 'h3', label: 'Übertragung von mehr Eigenverantwortung für ein Projekt', correctQuadrant: 'motivator', explanation: 'Verantwortung ist ein klassischer Motivator und schafft echte Zufriedenheit.' },
      { id: 'h4', label: 'Öffentliche Anerkennung einer besonders guten Leistung', correctQuadrant: 'motivator', explanation: 'Anerkennung wirkt als Motivator, nicht nur als Vermeidung von Unzufriedenheit.' },
      { id: 'h5', label: 'Ein klarer, fairer Verhaltenskodex im Unternehmen', correctQuadrant: 'hygiene', explanation: 'Unternehmenspolitik und -richtlinien sind Hygienefaktoren.' },
      { id: 'h6', label: 'Eine anspruchsvollere Aufgabe mit mehr Entwicklungsmöglichkeiten', correctQuadrant: 'motivator', explanation: 'Die Aufgabe selbst (Erfolg, Wachstum) wirkt motivierend.' },
    ],
  },
  {
    id: 'chancen-risiken-teamarbeit',
    title: 'Chancen & Risiken der Teamarbeit',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    scenario: 'Ihr Unternehmen überlegt, künftig mehr Aufgaben in festen Teams statt einzeln bearbeiten zu lassen.',
    instructions: 'Sortiere die folgenden Effekte danach, ob sie eine Chance oder ein Risiko der Teamarbeit darstellen.',
    columns: '1fr 1fr',
    rows: '1fr',
    areas: ['chance risiko'],
    accent: AMBER,
    quadrants: [
      { id: 'chance', area: 'chance', title: 'Chance', hint: 'spricht für Teamarbeit' },
      { id: 'risiko', area: 'risiko', title: 'Risiko', hint: 'spricht gegen Teamarbeit' },
    ],
    items: [
      { id: 'synergie', label: 'Synergieeffekte: "Das Ganze ist mehr als die Summe seiner Teile."', correctQuadrant: 'chance', explanation: 'Durch Kombination unterschiedlicher Kompetenzen entsteht mehr, als Einzelne leisten könnten.' },
      { id: 'innovation', label: 'Erhöhte Innovationskraft durch gesteigerte Kreativität im Team.', correctQuadrant: 'chance', explanation: 'Unterschiedliche Perspektiven im Team fördern neue Ideen.' },
      { id: 'entscheidung', label: 'Höhere Entscheidungsqualität und -akzeptanz durch gemeinsame Beratung.', correctQuadrant: 'chance', explanation: 'Mehr Perspektiven verbessern die Entscheidungsgrundlage und die Akzeptanz im Team.' },
      { id: 'socialloafing', label: 'Leistungsverluste durch Social Loafing — Einzelne reduzieren unbewusst ihre Anstrengung.', correctQuadrant: 'risiko', explanation: 'In Gruppen sinkt oft die individuell wahrgenommene Verantwortung für das Ergebnis.' },
      { id: 'groupthink', label: 'Gefahr von "Groupthink" — Kritik und Widerspruch werden vermieden.', correctQuadrant: 'risiko', explanation: 'Der Wunsch nach Harmonie im Team kann kritisches Hinterfragen unterdrücken.' },
      { id: 'verantwortungsdiffusion', label: 'Verantwortungsdiffusion durch reduzierte Eigenverantwortung Einzelner.', correctQuadrant: 'risiko', explanation: 'Wenn viele verantwortlich sind, fühlt sich am Ende oft niemand richtig zuständig.' },
    ],
  },
  {
    id: 'reifegrad-anwenden',
    title: 'Reifegradmodell anwenden',
    area: 'fuehrung',
    difficulty: 'fortgeschritten',
    scenario: 'Als Führungskraft treffen Sie auf Mitarbeitende mit ganz unterschiedlichem Reifegrad bezüglich derselben Aufgabe.',
    instructions: 'Ordne jede Mitarbeiterbeschreibung dem passenden Führungsstil nach Hersey/Blanchard zu.',
    columns: '1fr 1fr 1fr 1fr',
    rows: '1fr',
    areas: ['telling selling participating delegating'],
    accent: AMBER,
    quadrants: [
      { id: 'telling', area: 'telling', title: 'Telling (S1)', hint: 'M1: kann/will nicht' },
      { id: 'selling', area: 'selling', title: 'Selling (S2)', hint: 'M2: will, kann noch nicht' },
      { id: 'participating', area: 'participating', title: 'Participating (S3)', hint: 'M3: kann, will unsicher' },
      { id: 'delegating', area: 'delegating', title: 'Delegating (S4)', hint: 'M4: kann und will' },
    ],
    items: [
      { id: 'reif1', label: 'Ein neuer Auszubildender kennt die Abläufe noch nicht und ist unsicher, ob er die Aufgabe überhaupt schafft.', correctQuadrant: 'telling', explanation: 'Reifegrad M1: weder Können noch Wollen ausgeprägt — klare Anweisungen und enge Kontrolle sind nötig.' },
      { id: 'reif2', label: 'Ein Praktikant hat noch kaum Erfahrung, ist aber hoch motiviert und will sich unbedingt beweisen.', correctQuadrant: 'selling', explanation: 'Reifegrad M2: hohe Motivation, aber noch fachliche Lücken — die Führungskraft erklärt und unterstützt.' },
      { id: 'reif3', label: 'Eine erfahrene Mitarbeiterin kann die Aufgabe fachlich gut, traut sich aber nicht recht zu, allein zu entscheiden.', correctQuadrant: 'participating', explanation: 'Reifegrad M3: Können ist da, aber Unsicherheit bremst — gemeinsames Entscheiden und Ermutigung helfen.' },
      { id: 'reif4', label: 'Ein langjähriger Experte erledigt diese Aufgabe seit Jahren zuverlässig und völlig selbstständig.', correctQuadrant: 'delegating', explanation: 'Reifegrad M4: kann und will — Verantwortung wird vollständig übergeben.' },
      { id: 'reif5', label: 'Ein Mitarbeiter hat wiederholt Fehler gemacht und wirkt inzwischen völlig demotiviert für diese Aufgabe.', correctQuadrant: 'telling', explanation: 'Geringes Können und geringe Motivation entsprechen wieder M1 — klare Struktur schafft Sicherheit.' },
      { id: 'reif6', label: 'Eine neue Kollegin brennt für die Aufgabe, hat aber noch keinerlei praktische Erfahrung damit gesammelt.', correctQuadrant: 'selling', explanation: 'Hohe Motivation bei noch fehlender Erfahrung entspricht M2.' },
      { id: 'reif7', label: 'Ein Teammitglied beherrscht die Aufgabe technisch einwandfrei, zögert aber, eigenständig Entscheidungen zu treffen.', correctQuadrant: 'participating', explanation: 'Fachliches Können bei geringem Selbstvertrauen entspricht M3.' },
      { id: 'reif8', label: 'Eine Senior-Mitarbeiterin optimiert den Prozess sogar eigenständig und schult neue Kollegen darin ein.', correctQuadrant: 'delegating', explanation: 'Höchstes Können und höchste Eigenmotivation entsprechen M4.' },
    ],
  },
  {
    id: 'tuckman-teamentwicklung',
    title: 'Teamentwicklung nach Tuckman',
    area: 'fuehrung',
    difficulty: 'fortgeschritten',
    scenario: 'Ein neu zusammengestelltes Projektteam durchläuft im Laufe der Zusammenarbeit typische Entwicklungsphasen.',
    instructions: 'Ordne jede Beobachtung der passenden Tuckman-Phase zu.',
    columns: '1fr 1fr 1fr 1fr 1fr',
    rows: '1fr',
    areas: ['forming storming norming performing adjourning'],
    accent: AMBER,
    quadrants: [
      { id: 'forming', area: 'forming', title: 'Forming', hint: 'Orientierung' },
      { id: 'storming', area: 'storming', title: 'Storming', hint: 'Konflikt' },
      { id: 'norming', area: 'norming', title: 'Norming', hint: 'Regelfindung' },
      { id: 'performing', area: 'performing', title: 'Performing', hint: 'Leistung' },
      { id: 'adjourning', area: 'adjourning', title: 'Adjourning', hint: 'Auflösung' },
    ],
    items: [
      { id: 'form1', label: 'Die Teammitglieder sind noch unsicher, höflich und zurückhaltend zueinander.', correctQuadrant: 'forming', explanation: 'Forming: Orientierungsphase — Rollen und Ziele sind noch unklar.' },
      { id: 'form2', label: 'Rollen und Zuständigkeiten im Team sind noch völlig offen.', correctQuadrant: 'forming', explanation: 'Forming: Das Team sucht noch nach Struktur und gegenseitigem Kennenlernen.' },
      { id: 'storm1', label: 'Erste Konflikte um Rollen, Kompetenzen und Vorgehen brechen offen auf.', correctQuadrant: 'storming', explanation: 'Storming: Machtkämpfe und Meinungsverschiedenheiten sind typisch für diese Phase.' },
      { id: 'storm2', label: 'Einzelne Teammitglieder konkurrieren offen um Einfluss und Anerkennung.', correctQuadrant: 'storming', explanation: 'Storming: Konkurrenz um Positionen prägt die Zusammenarbeit noch stark.' },
      { id: 'norm1', label: 'Regeln und Rollen werden akzeptiert, ein gemeinsamer Konsens entsteht.', correctQuadrant: 'norming', explanation: 'Norming: Das Team einigt sich auf gemeinsame Normen und Arbeitsweisen.' },
      { id: 'norm2', label: 'Der Zusammenhalt wächst, Kritik wird zunehmend konstruktiv geäußert.', correctQuadrant: 'norming', explanation: 'Norming: Vertrauen und Kooperationsbereitschaft nehmen spürbar zu.' },
      { id: 'perf1', label: 'Das Team arbeitet eigenständig, effizient und lösungsorientiert an der Aufgabe.', correctQuadrant: 'performing', explanation: 'Performing: Die Energie fließt fast vollständig in die eigentliche Aufgabe.' },
      { id: 'perf2', label: 'Entscheidungen werden schnell und ohne große Reibungsverluste getroffen.', correctQuadrant: 'performing', explanation: 'Performing: Das Team hat sein höchstes Leistungsniveau erreicht.' },
      { id: 'adj1', label: 'Das Team löst sich nach Projektende auf, Ergebnisse werden gemeinsam reflektiert.', correctQuadrant: 'adjourning', explanation: 'Adjourning: Abschluss und Rückblick auf die gemeinsame Zusammenarbeit.' },
      { id: 'adj2', label: 'Abschied und Wertschätzung der gemeinsamen Zusammenarbeit stehen im Vordergrund.', correctQuadrant: 'adjourning', explanation: 'Adjourning: Das Team würdigt die geleistete Arbeit, bevor es sich auflöst.' },
    ],
  },
  {
    id: 'eskalationsstufen-glasl',
    title: 'Eskalationsstufen nach Glasl',
    area: 'fuehrung',
    difficulty: 'fortgeschritten',
    scenario: 'Ein schwelender Konflikt zwischen zwei Abteilungen hat sich über mehrere Monate entwickelt.',
    instructions: 'Ordne jede Beobachtung der passenden Eskalationsphase nach Glasl zu.',
    columns: '1fr 1fr 1fr',
    rows: '1fr',
    areas: ['phase1 phase2 phase3'],
    accent: AMBER,
    quadrants: [
      { id: 'phase1', area: 'phase1', title: '1. Phase', hint: 'noch konstruktiv' },
      { id: 'phase2', area: 'phase2', title: '2. Phase', hint: 'destruktiv' },
      { id: 'phase3', area: 'phase3', title: '3. Phase', hint: 'selbstzerstörerisch' },
    ],
    items: [
      { id: 'g1', label: 'Beide Seiten sind noch bereit, in einem klärenden Gespräch eine Lösung zu suchen.', correctQuadrant: 'phase1', explanation: 'Auf konstruktivem Niveau helfen meist noch klärende Gespräche.' },
      { id: 'g2', label: 'Erste Meinungsverschiedenheiten führen zu Spannungen, aber man redet noch direkt miteinander.', correctQuadrant: 'phase1', explanation: 'Noch überschaubares, konstruktives Konfliktniveau.' },
      { id: 'g3', label: 'Die direkte Kommunikation ist abgebrochen, eine externe Moderation wird eingeschaltet.', correctQuadrant: 'phase2', explanation: 'Reicht das direkte Gespräch nicht mehr, wird häufig eine Moderation notwendig.' },
      { id: 'g4', label: 'Beide Seiten bilden Lager und suchen aktiv Verbündete gegen die andere Abteilung.', correctQuadrant: 'phase2', explanation: 'Zeichen einer destruktiven Konfliktdynamik.' },
      { id: 'g5', label: 'Es kommt zu einem offenen Machteingriff durch die Geschäftsführung, keine Seite sucht mehr Konsens.', correctQuadrant: 'phase3', explanation: 'Auf der am weitesten fortgeschrittenen Stufe hilft nur noch ein Machteingriff von außen.' },
      { id: 'g6', label: 'Beiden Parteien ist der eigene Schaden inzwischen egal, Hauptsache die andere Seite verliert auch.', correctQuadrant: 'phase3', explanation: 'Selbstzerstörerisches Verhalten kennzeichnet die letzte Eskalationsstufe.' },
    ],
  },
  {
    id: 'wandel-typen-einordnen',
    title: 'Revolutionärer vs. evolutionärer Wandel',
    area: 'fuehrung',
    difficulty: 'profi',
    scenario: 'Verschiedene Unternehmen stehen vor unterschiedlichen Arten von Veränderungsprojekten.',
    instructions: 'Ordne jedes Szenario dem passenden Wandel-Typ zu.',
    columns: '1fr 1fr',
    rows: '1fr',
    areas: ['revolution evolution'],
    accent: AMBER,
    quadrants: [
      { id: 'revolution', area: 'revolution', title: 'Revolutionärer Wandel', hint: 'hoher Druck, kurzfristig' },
      { id: 'evolution', area: 'evolution', title: 'Evolutionärer Wandel', hint: 'geringer Druck, langfristig' },
    ],
    items: [
      { id: 'w1', label: 'Nach einer plötzlichen Insolvenzgefahr muss binnen Wochen ein radikales Sanierungsprogramm umgesetzt werden.', correctQuadrant: 'revolution', explanation: 'Hoher akuter Druck und kurzer Zeithorizont sind typisch für revolutionären Wandel.' },
      { id: 'w2', label: 'Ein Unternehmen plant über drei Jahre hinweg einen schrittweisen Kulturwandel hin zu mehr Eigenverantwortung.', correctQuadrant: 'evolution', explanation: 'Langfristiger Horizont bei geringem akutem Druck entspricht evolutionärem Wandel.' },
      { id: 'w3', label: 'Ein Konkurrenzangriff zwingt zu einer ad-hoc-Reorganisation innerhalb eines Monats.', correctQuadrant: 'revolution', explanation: 'Unvorhersehbare Krise mit hartem, kurzfristigem Handlungsdruck.' },
      { id: 'w4', label: 'Die IT-Abteilung führt über zwei Jahre kontinuierliche, gut geplante Prozessverbesserungen ein.', correctQuadrant: 'evolution', explanation: 'Planbare, kontrollierbare Organisationsentwicklung ohne akuten Druck.' },
    ],
  },
  {
    id: 'streich-veraenderungsphasen',
    title: 'Der emotionale Prozess des Wandels (Streich)',
    area: 'fuehrung',
    difficulty: 'profi',
    scenario: 'Mitarbeitende reagieren auf eine angekündigte Umstrukturierung mit ganz unterschiedlichen Emotionen — je nachdem, wie weit sie im Veränderungsprozess sind.',
    instructions: 'Ordne jede emotionale Reaktion der passenden Prozessphase nach Streich zu.',
    columns: '1fr 1fr 1fr',
    rows: '1fr',
    areas: ['frueh tal spaet'],
    accent: AMBER,
    quadrants: [
      { id: 'frueh', area: 'frueh', title: 'Frühphase', hint: 'Verneinung, Angst, Widerstand' },
      { id: 'tal', area: 'tal', title: '„Tal der Tränen"', hint: 'rationale Einsicht, Trauer' },
      { id: 'spaet', area: 'spaet', title: 'Spätphase', hint: 'Öffnung, Integration' },
    ],
    items: [
      { id: 's1', label: '"Das betrifft uns doch gar nicht wirklich" — die Nachricht wird zunächst verdrängt.', correctQuadrant: 'frueh', explanation: 'Verneinung ist die erste emotionale Reaktion auf angekündigten Wandel.' },
      { id: 's2', label: 'Ein Mitarbeiter reagiert mit offenem Ärger und Widerstand gegen die Pläne.', correctQuadrant: 'frueh', explanation: 'Widerstand (Ärger, Wut) gehört noch zur frühen Phase der Ablehnung.' },
      { id: 's3', label: 'Rational leuchtet die Notwendigkeit der Veränderung inzwischen ein, trotzdem herrscht Frustration.', correctQuadrant: 'tal', explanation: 'Rationale Einsicht bei gleichzeitiger emotionaler Frustration kennzeichnet das "Tal der Tränen".' },
      { id: 's4', label: 'Es macht sich eine spürbare Trauer über das Alte breit, das nun losgelassen werden muss.', correctQuadrant: 'tal', explanation: 'Emotionale Akzeptanz und Trauer sind der Tiefpunkt der Kurve.' },
      { id: 's5', label: 'Erste Neugier auf die neuen Möglichkeiten kommt auf, man probiert Neues aus.', correctQuadrant: 'spaet', explanation: 'Öffnung mit Neugier und Enthusiasmus leitet die spätere Phase ein.' },
      { id: 's6', label: 'Der neue Zustand wird mit Zuversicht und Selbstvertrauen angenommen.', correctQuadrant: 'spaet', explanation: 'Integration mit Selbstvertrauen und Freude bildet den Abschluss des Prozesses.' },
    ],
  },

  // ---------------------------------------------------------- STRATEGIE
  {
    id: 'swot-anwenden',
    title: 'SWOT anwenden: Die Stadtbäckerei',
    area: 'strategie',
    difficulty: 'anfaenger',
    scenario: 'Eine seit 40 Jahren familiengeführte Stadtbäckerei überlegt, einen Online-Shop mit Lieferservice zu eröffnen.',
    instructions: 'Ordne jede Beobachtung der passenden SWOT-Kategorie zu.',
    columns: '1fr 1fr',
    rows: '1fr 1fr',
    areas: ['staerken schwaechen', 'chancen risiken'],
    accent: TEAL,
    quadrants: [
      { id: 'staerken', area: 'staerken', title: 'Stärken', hint: 'intern, positiv' },
      { id: 'schwaechen', area: 'schwaechen', title: 'Schwächen', hint: 'intern, negativ' },
      { id: 'chancen', area: 'chancen', title: 'Chancen', hint: 'extern, positiv' },
      { id: 'risiken', area: 'risiken', title: 'Risiken', hint: 'extern, negativ' },
    ],
    items: [
      { id: 'sw1', label: 'Die Bäckerei genießt seit Jahrzehnten einen exzellenten Ruf und treue Stammkundschaft.', correctQuadrant: 'staerken', explanation: 'Ein interner Vorteil: Markenvertrauen, das dem Unternehmen selbst gehört.' },
      { id: 'sw2', label: 'Rezepte und Backprozesse sind über Generationen ausgereift und schmecken einzigartig gut.', correctQuadrant: 'staerken', explanation: 'Interne Kernkompetenz, die schwer zu kopieren ist.' },
      { id: 'sw3', label: 'Niemand im Team hat Erfahrung mit Online-Shops oder digitalem Marketing.', correctQuadrant: 'schwaechen', explanation: 'Eine interne Lücke, die das Unternehmen selbst beheben muss.' },
      { id: 'sw4', label: 'Die vorhandene Küche hat keine Kapazität für zusätzliche Lieferaufträge.', correctQuadrant: 'schwaechen', explanation: 'Interne Ressourcenbegrenzung, die die Umsetzung erschwert.' },
      { id: 'sw5', label: 'Immer mehr Menschen in der Umgebung bestellen Lebensmittel und Backwaren online.', correctQuadrant: 'chancen', explanation: 'Ein Trend im Marktumfeld, den das Unternehmen nutzen könnte.' },
      { id: 'sw6', label: 'Die Stadt fördert lokale Betriebe, die auf nachhaltige Lieferdienste umstellen.', correctQuadrant: 'chancen', explanation: 'Eine externe Rahmenbedingung, die zusätzlich unterstützt.' },
      { id: 'sw7', label: 'Ein großer Lieferdienst-Konzern plant, in der Region eigene Backwaren anzubieten.', correctQuadrant: 'risiken', explanation: 'Eine externe Bedrohung durch einen neuen, finanzstarken Wettbewerber.' },
      { id: 'sw8', label: 'Steigende Mehl- und Energiepreise könnten die Margen der ganzen Branche belasten.', correctQuadrant: 'risiken', explanation: 'Eine externe wirtschaftliche Entwicklung außerhalb der eigenen Kontrolle.' },
    ],
  },
  {
    id: 'wertschoepfungskette-anwenden',
    title: 'Primäre oder sekundäre Aktivität?',
    area: 'strategie',
    difficulty: 'anfaenger',
    scenario: 'Ein Fertigungsunternehmen möchte seine Tätigkeiten nach der Wertschöpfungskette einordnen.',
    instructions: 'Ordne jede Tätigkeit der passenden Kategorie zu.',
    columns: '1fr 1fr',
    rows: '1fr',
    areas: ['primaer sekundaer'],
    accent: TEAL,
    quadrants: [
      { id: 'primaer', area: 'primaer', title: 'Primäre Aktivität', hint: 'direkte Leistungserstellung' },
      { id: 'sekundaer', area: 'sekundaer', title: 'Sekundäre Aktivität', hint: 'unterstützt die Leistungserstellung' },
    ],
    items: [
      { id: 'wa1', label: 'Wareneingangskontrolle der angelieferten Rohstoffe', correctQuadrant: 'primaer', explanation: 'Teil der Eingangslogistik — einer primären Aktivität.' },
      { id: 'wa2', label: 'Auslieferung der fertigen Produkte an die Kunden', correctQuadrant: 'primaer', explanation: 'Teil der Ausgangslogistik.' },
      { id: 'wa3', label: 'Eine Werbekampagne für ein neues Produkt', correctQuadrant: 'primaer', explanation: 'Teil von Marketing & Vertrieb.' },
      { id: 'wa4', label: 'Die Personalabteilung rekrutiert neue Fachkräfte für die Produktion.', correctQuadrant: 'sekundaer', explanation: 'Personalmanagement unterstützt die Leistungserstellung abteilungsübergreifend.' },
      { id: 'wa5', label: 'Der IT-Support wartet die unternehmensweite Warenwirtschaftssoftware.', correctQuadrant: 'sekundaer', explanation: 'Technologiemanagement ist eine sekundäre, unterstützende Aktivität.' },
      { id: 'wa6', label: 'Die Einkaufsabteilung verhandelt Rahmenverträge mit neuen Zulieferern.', correctQuadrant: 'sekundaer', explanation: 'Beschaffung von Produktionsfaktoren zählt zu den sekundären Aktivitäten.' },
    ],
  },
  {
    id: 'five-forces-flugbranche',
    title: 'Five-Forces anwenden: Die Flugbranche',
    area: 'strategie',
    difficulty: 'fortgeschritten',
    scenario: 'Die Fluglinienbranche ist durch geringe Renditen und starken Wettbewerb zwischen etablierten Hochkosten-Airlines und neuen Billigfluglinien gekennzeichnet.',
    instructions: 'Ordne jede Beobachtung der passenden Five-Forces-Kraft zu.',
    columns: '1fr 1fr 1fr 1fr 1fr',
    rows: '1fr',
    areas: ['wettbewerb neu kunden lieferanten substitute'],
    accent: TEAL,
    quadrants: [
      { id: 'wettbewerb', area: 'wettbewerb', title: 'Wettbewerber', hint: 'Branchenwettbewerb' },
      { id: 'neu', area: 'neu', title: 'Neue Wettbewerber', hint: 'Markteintritt' },
      { id: 'kunden', area: 'kunden', title: 'Kunden', hint: 'Käufermacht' },
      { id: 'lieferanten', area: 'lieferanten', title: 'Lieferanten', hint: 'Lieferantenmacht' },
      { id: 'substitute', area: 'substitute', title: 'Substitute', hint: 'Ersatzangebote' },
    ],
    items: [
      { id: 'flug1', label: 'Etablierte Airlines konkurrieren stark über Sicherheit, Service und Vielflieger-Programme.', correctQuadrant: 'wettbewerb', explanation: 'Direkte Rivalität zwischen bereits in der Branche aktiven Fluggesellschaften.' },
      { id: 'flug2', label: 'Billigflieger und Hochkosten-Airlines liefern sich einen intensiven Preiskampf.', correctQuadrant: 'wettbewerb', explanation: 'Auch der Wettbewerb zwischen unterschiedlichen Strategietypen zählt zum Branchenwettbewerb.' },
      { id: 'flug3', label: 'Eine neue Billigfluglinie könnte mit sehr niedrigen Einstiegspreisen in den Markt drängen.', correctQuadrant: 'neu', explanation: 'Die Gefahr durch neue Marktteilnehmer hängt von den Eintrittsbarrieren der Branche ab.' },
      { id: 'flug4', label: 'Hohe Kosten für Flugzeugflotte, Landerechte und IT-Systeme erschweren den Markteintritt.', correctQuadrant: 'neu', explanation: 'Hohe Eintrittsbarrieren senken die Bedrohung durch neue Wettbewerber.' },
      { id: 'flug5', label: 'Freizeitkunden achten hauptsächlich auf den günstigsten Preis und wechseln leicht den Anbieter.', correctQuadrant: 'kunden', explanation: 'Geringe Wechselkosten und Preissensibilität stärken die Verhandlungsmacht der Kunden.' },
      { id: 'flug6', label: 'Geschäftskunden sind weniger preissensibel und legen mehr Wert auf Flexibilität und Komfort.', correctQuadrant: 'kunden', explanation: 'Unterschiedliche Kundengruppen haben unterschiedlich starke Verhandlungsmacht.' },
      { id: 'flug7', label: 'Fluggesellschaften benötigen große Mengen an Kerosin und sind von wenigen Öllieferanten abhängig.', correctQuadrant: 'lieferanten', explanation: 'Wenige, wichtige Lieferanten für einen zentralen Rohstoff stärken deren Verhandlungsmacht.' },
      { id: 'flug8', label: 'Nur zwei große Flugzeughersteller (Boeing, Airbus) beliefern nahezu den gesamten Weltmarkt.', correctQuadrant: 'lieferanten', explanation: 'Ein stark konzentrierter Anbietermarkt erhöht die Lieferantenmacht deutlich.' },
      { id: 'flug9', label: 'Bahn- oder Fernbusverbindungen könnten auf innereuropäischen Kurzstrecken eine günstigere Alternative sein.', correctQuadrant: 'substitute', explanation: 'Alternative Verkehrsmittel gefährden bei kurzen Distanzen den Nutzen des Fliegens.' },
      { id: 'flug10', label: 'Videokonferenzen ersetzen zunehmend Geschäftsreisen, die früher per Flugzeug stattfanden.', correctQuadrant: 'substitute', explanation: 'Digitale Alternativen können ganze Reiseanlässe überflüssig machen.' },
    ],
  },
  {
    id: 'generische-strategien-anwenden',
    title: 'Generische Strategien anwenden',
    area: 'strategie',
    difficulty: 'fortgeschritten',
    scenario: 'Verschiedene Automobilhersteller verfolgen sehr unterschiedliche Wettbewerbsstrategien.',
    instructions: 'Ordne jedes Unternehmensbeispiel der passenden generischen Strategie nach Porter zu.',
    columns: '1fr 1fr 1fr',
    rows: '1fr',
    areas: ['diff kf konz'],
    accent: TEAL,
    quadrants: [
      { id: 'diff', area: 'diff', title: 'Differenzierung', hint: 'Einzigartigkeit, Gesamtmarkt' },
      { id: 'kf', area: 'kf', title: 'Kostenführerschaft', hint: 'Kostenminimum, Gesamtmarkt' },
      { id: 'konz', area: 'konz', title: 'Konzentration', hint: 'Nischenmarkt' },
    ],
    items: [
      { id: 'gsa1', label: 'Ein Hersteller wirbt mit einzigartigem Markenimage und Produktdesign für den Massenmarkt.', correctQuadrant: 'diff', explanation: 'Wettbewerb über eine vom Kunden als einzigartig empfundene Leistung im Gesamtmarkt.' },
      { id: 'gsa2', label: 'Ein Hersteller bietet vergleichbare Fahrzeuge zum niedrigsten Preis der Branche an.', correctQuadrant: 'kf', explanation: 'Wettbewerb über den Preis bei vergleichbarem Produkt, gestützt auf Kostenvorteile.' },
      { id: 'gsa3', label: 'Ein Hersteller konzentriert sich ausschließlich auf handgefertigte Luxus-Sportwagen für eine kleine Zielgruppe.', correctQuadrant: 'konz', explanation: 'Beschränkung auf einen Nischenmarkt statt den Gesamtmarkt zu bedienen.' },
      { id: 'gsa4', label: 'Ein Hersteller senkt durch Massenproduktion und Skaleneffekte konsequent seine Stückkosten.', correctQuadrant: 'kf', explanation: 'Kernkompetenz in Einkauf, Produktion und Logistik zur Kostenminimierung.' },
      { id: 'gsa5', label: 'Ein Hersteller bietet ausschließlich Elektro-Kleinwagen für urbane Nischenkunden mit besonderem Fokus an.', correctQuadrant: 'konz', explanation: 'Fokus auf ein enges Marktsegment statt breiter Marktabdeckung.' },
      { id: 'gsa6', label: 'Ein Hersteller positioniert sich über technologische Innovationskraft und Alleinstellungsmerkmale am Gesamtmarkt.', correctQuadrant: 'diff', explanation: 'Differenzierung über wahrgenommene Einzigartigkeit statt über den Preis.' },
    ],
  },
  {
    id: 'vier-c-flugbranche',
    title: '4-C-Konzept anwenden: Die Flugbranche',
    area: 'strategie',
    difficulty: 'profi',
    scenario: 'Warum überleben etablierte Hochkostenfluglinien, während viele neue Billigfluglinien nach der Deregulierung scheiterten? Die Antwort liefert das 4-C-Konzept.',
    instructions: 'Ordne jede Beobachtung der passenden 4-C-Dimension zu.',
    columns: '1fr 1fr 1fr 1fr',
    rows: '1fr',
    areas: ['customer competition costs capabilities'],
    accent: TEAL,
    quadrants: [
      { id: 'customer', area: 'customer', title: 'Customer', hint: 'Kunden' },
      { id: 'competition', area: 'competition', title: 'Competition', hint: 'Wettbewerb' },
      { id: 'costs', area: 'costs', title: 'Costs', hint: 'Kosten' },
      { id: 'capabilities', area: 'capabilities', title: 'Capabilities', hint: 'Fähigkeiten' },
    ],
    items: [
      { id: 'v4c1', label: 'Geschäftsreisende sind weniger preissensibel und legen Wert auf Flexibilität.', correctQuadrant: 'customer', explanation: 'Beschreibt Bedürfnisse einer Kundengruppe — die Customer-Dimension.' },
      { id: 'v4c2', label: 'Zwischen etablierten und Billigfluglinien herrscht ein intensiver Preiskampf.', correctQuadrant: 'competition', explanation: 'Beschreibt die Wettbewerbsdynamik der Branche.' },
      { id: 'v4c3', label: 'Treibstoff und Flugzeugleasing machen einen Großteil der Kostenstruktur aus.', correctQuadrant: 'costs', explanation: 'Beschreibt die Hauptkostentreiber der Anbieter.' },
      { id: 'v4c4', label: 'Hochmoderne IT-Systeme fürs Yield Management passen Preise in Echtzeit an Angebot und Nachfrage an.', correctQuadrant: 'capabilities', explanation: 'Die entscheidende Kompetenz, die Hochkostenfluglinien von Billigfliegern unterscheidet.' },
      { id: 'v4c5', label: 'Freizeitkunden wählen fast ausschließlich nach dem günstigsten Preis.', correctQuadrant: 'customer', explanation: 'Auch das ist eine Beschreibung von Kundenbedürfnissen — nur einer anderen Kundengruppe.' },
      { id: 'v4c6', label: 'Hochqualifiziertes Personal im Pricing gilt als schwer kopierbarer Wettbewerbsvorteil.', correctQuadrant: 'capabilities', explanation: 'Eine Kernkompetenz, die den entscheidenden Unterschied ausmacht.' },
    ],
  },
  {
    id: 'perspektiven-zuordnen',
    title: 'Frameworks: Intern, extern oder gemischt?',
    area: 'strategie',
    difficulty: 'profi',
    scenario: 'Für die Klausur ist wichtig zu wissen, aus welcher Perspektive ein Rahmenkonzept ein Unternehmen betrachtet.',
    instructions: 'Ordne jedes Framework der passenden Perspektive zu.',
    columns: '1fr 1fr 1fr',
    rows: '1fr',
    areas: ['intern extern gemischt'],
    accent: TEAL,
    quadrants: [
      { id: 'intern', area: 'intern', title: 'Intern', hint: 'nur unternehmensbezogen' },
      { id: 'extern', area: 'extern', title: 'Extern', hint: 'nur marktbezogen' },
      { id: 'gemischt', area: 'gemischt', title: 'Gemischt', hint: 'intern und extern' },
    ],
    items: [
      { id: 'p1', label: 'Wertschöpfungskette', correctQuadrant: 'intern', explanation: 'Analysiert ausschließlich die internen primären und sekundären Aktivitäten.' },
      { id: 'p2', label: 'Five-Forces-Modell', correctQuadrant: 'extern', explanation: 'Betrachtet ausschließlich das Wettbewerbsumfeld der Branche.' },
      { id: 'p3', label: 'SWOT-Analyse', correctQuadrant: 'gemischt', explanation: 'Kombiniert interne Stärken/Schwächen mit externen Chancen/Risiken.' },
      { id: 'p4', label: '4-C-Konzept', correctQuadrant: 'gemischt', explanation: 'Betrachtet sowohl interne (Costs, Capabilities) als auch externe Faktoren (Customer, Competition).' },
      { id: 'p5', label: 'BCG-Portfolio', correctQuadrant: 'gemischt', explanation: 'Kombiniert internen Marktanteil mit externem Marktwachstum.' },
      { id: 'p6', label: 'Generische Strategien nach Porter', correctQuadrant: 'gemischt', explanation: 'Verknüpft die interne Wahl des strategischen Vorteils mit der externen Marktausrichtung.' },
    ],
  },
];

export const TERM_MATCH_SETS: TermMatchSet[] = [
  // ---------------------------------------------------------- FÜHRUNG
  {
    id: 'fuehrungsdefinition-jung',
    title: 'Führungsdefinition nach Jung',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: AMBER,
    blanks: [
      { id: 'fj1', before: 'Nach Jung ist Personalführung ein ', correctTermId: 'kommunikativer-prozess' },
      { id: 'fj2', before: ' der ', correctTermId: 'einflussnahme' },
      { id: 'fj3', before: ' auf die Mitarbeiter zum Zweck ', correctTermId: 'zielgerichteter' },
    ],
    tail: ' Leistungserstellung.',
    terms: [
      { id: 'kommunikativer-prozess', text: 'kommunikativer Prozess' },
      { id: 'einflussnahme', text: 'Einflussnahme' },
      { id: 'zielgerichteter', text: 'zielgerichteter' },
    ],
    distractors: [
      { id: 'kontrollprozess', text: 'Kontrollprozess' },
      { id: 'freiwilliger', text: 'freiwilliger' },
    ],
  },
  {
    id: 'fuehrungseffizienz',
    title: 'Führungseffizienz',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: AMBER,
    blanks: [
      { id: 'b1', before: 'Mitarbeiterführung ist nicht zweckfrei, sondern dient der Zielerreichung, der ', correctTermId: 'fuehrungseffizienz' },
      { id: 'b2', before: '. Man unterscheidet dabei zwei Dimensionen: Die ', correctTermId: 'wirtschaftliche-effizienz' },
      { id: 'b3', before: ' beschreibt den Grad der Erreichung institutioneller Ziele (ökonomischer Aspekt). Die ', correctTermId: 'soziale-effizienz' },
    ],
    tail: ' beschreibt den Grad der Befriedigung individueller Bedürfnisse der Mitarbeiter (humaner Aspekt).',
    terms: [
      { id: 'fuehrungseffizienz', text: 'Führungseffizienz' },
      { id: 'wirtschaftliche-effizienz', text: 'wirtschaftliche Effizienz' },
      { id: 'soziale-effizienz', text: 'soziale Effizienz' },
    ],
    distractors: [
      { id: 'fuehrungsspanne', text: 'Führungsspanne' },
      { id: 'delegation', text: 'Delegation' },
    ],
  },
  {
    id: 'smart-ziele',
    title: 'SMART-Ziele',
    area: 'fuehrung',
    difficulty: 'anfaenger',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: AMBER,
    blanks: [
      { id: 'sm1', before: 'Ziele sollten nach dem SMART-Prinzip formuliert werden: Sie sind ', correctTermId: 'spezifisch' },
      { id: 'sm2', before: ' (klar und eindeutig formuliert), ', correctTermId: 'messbar' },
      { id: 'sm3', before: ' (durch Kennzahlen überprüfbar), ', correctTermId: 'attraktiv' },
      { id: 'sm4', before: ' (herausfordernd, aber motivierend), ', correctTermId: 'realistisch' },
      { id: 'sm5', before: ' (unter den gegebenen Bedingungen erreichbar) sowie ', correctTermId: 'terminiert' },
    ],
    tail: ' (mit einem klaren Termin versehen).',
    terms: [
      { id: 'spezifisch', text: 'spezifisch' },
      { id: 'messbar', text: 'messbar' },
      { id: 'attraktiv', text: 'attraktiv' },
      { id: 'realistisch', text: 'realistisch' },
      { id: 'terminiert', text: 'terminiert' },
    ],
    distractors: [
      { id: 'flexibel', text: 'flexibel' },
      { id: 'delegierbar', text: 'delegierbar' },
    ],
  },
  {
    id: 'zuhoeren-stufen',
    title: 'Die vier Stufen des Zuhörens',
    area: 'fuehrung',
    difficulty: 'fortgeschritten',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: AMBER,
    blanks: [
      { id: 'z1', before: 'Zur Gesprächsführung gehören vier Stufen des Zuhörens. Beim ', correctTermId: 'aufmerksam' },
      { id: 'z2', before: ' Zuhören schenkt man dem Gesprächspartner volle Konzentration. Beim ', correctTermId: 'aktiv' },
      { id: 'z3', before: ' Zuhören spiegelt man das Gehörte in eigenen Worten. Das ', correctTermId: 'analytisch' },
      { id: 'z4', before: ' Zuhören zerlegt die Aussage gedanklich in ihre Bestandteile, und das ', correctTermId: 'empathisch' },
    ],
    tail: ' Zuhören versucht zusätzlich, sich in die Gefühlslage des Gegenübers hineinzuversetzen.',
    terms: [
      { id: 'aufmerksam', text: 'aufmerksamen' },
      { id: 'aktiv', text: 'aktiven' },
      { id: 'analytisch', text: 'analytische' },
      { id: 'empathisch', text: 'empathische' },
    ],
    distractors: [
      { id: 'passiv', text: 'passive' },
      { id: 'kritisch', text: 'kritische' },
    ],
  },
  {
    id: 'vier-seiten-nachricht',
    title: 'Vier-Seiten-einer-Nachricht',
    area: 'fuehrung',
    difficulty: 'fortgeschritten',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: AMBER,
    blanks: [
      { id: 'v1', before: 'Nach Schulz von Thun enthält jede Nachricht vier Seiten. Die ', correctTermId: 'sachinfo' },
      { id: 'v2', before: ' informiert sachlich über einen Sachverhalt. Die ', correctTermId: 'selbstkundgabe' },
      { id: 'v3', before: ' gibt Auskunft darüber, was der Sender von sich selbst preisgibt. Der ', correctTermId: 'beziehungshinweis' },
      { id: 'v4', before: ' zeigt, wie Sender und Empfänger zueinander stehen. Der ', correctTermId: 'appell' },
    ],
    tail: ' drückt aus, wozu der Sender den Empfänger veranlassen möchte.',
    terms: [
      { id: 'sachinfo', text: 'Sachinformation' },
      { id: 'selbstkundgabe', text: 'Selbstkundgabe' },
      { id: 'beziehungshinweis', text: 'Beziehungshinweis' },
      { id: 'appell', text: 'Appell' },
    ],
    distractors: [
      { id: 'feedback', text: 'Feedback' },
      { id: 'ichbotschaft', text: 'Ich-Botschaft' },
    ],
  },
  {
    id: 'harvard-konzept',
    title: 'Harvard-Konzept',
    area: 'fuehrung',
    difficulty: 'profi',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: AMBER,
    blanks: [
      { id: 'h1', before: 'Das Harvard-Konzept nach Fisher/Ury (1991) beschreibt eine sachbezogene Verhandlungsführung nach vier Prinzipien: Erstens sollten ', correctTermId: 'menschen-probleme' },
      { id: 'h2', before: ' voneinander getrennt behandelt werden. Zweitens sollte man sich auf ', correctTermId: 'interessen' },
      { id: 'h3', before: ' konzentrieren statt auf starre Positionen. Drittens sollten ', correctTermId: 'entscheidungsoptionen' },
      { id: 'h4', before: ' zum beiderseitigen Vorteil entwickelt werden. Viertens sollten ', correctTermId: 'objektive-kriterien' },
    ],
    tail: ' zur Bewertung der Ergebnisse herangezogen werden.',
    terms: [
      { id: 'menschen-probleme', text: 'Menschen und Probleme' },
      { id: 'interessen', text: 'Interessen' },
      { id: 'entscheidungsoptionen', text: 'Entscheidungsoptionen' },
      { id: 'objektive-kriterien', text: 'objektive Kriterien' },
    ],
    distractors: [
      { id: 'emotionen-fakten', text: 'Emotionen und Fakten' },
      { id: 'positionen', text: 'Positionen' },
    ],
  },
  {
    id: 'herzberg-begriffe',
    title: "Herzbergs Zwei-Faktoren-Theorie",
    area: 'fuehrung',
    difficulty: 'profi',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: AMBER,
    blanks: [
      { id: 'hz1', before: 'Nach Herzberg entsteht Arbeitszufriedenheit über zwei unabhängige Faktorengruppen. ', correctTermId: 'hygienefaktoren' },
      { id: 'hz2', before: ' wie Gehalt und Arbeitsbedingungen verhindern zwar Unzufriedenheit, schaffen aber keine echte Zufriedenheit. Erst ', correctTermId: 'motivatoren' },
    ],
    tail: ' wie Anerkennung, Verantwortung und Erfolg schaffen echte, dauerhafte Zufriedenheit.',
    terms: [
      { id: 'hygienefaktoren', text: 'Hygienefaktoren' },
      { id: 'motivatoren', text: 'Motivatoren' },
    ],
    distractors: [
      { id: 'kernkompetenzen', text: 'Kernkompetenzen' },
      { id: 'leistungsanreize', text: 'Leistungsanreize' },
    ],
  },
  {
    id: 'change-typen-begriffe',
    title: 'Wandel-Typen und Kraftfeld-Ansatz',
    area: 'fuehrung',
    difficulty: 'profi',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: AMBER,
    blanks: [
      { id: 'ct1', before: 'Bei hohem Veränderungsdruck und kurzem Zeithorizont spricht man von ', correctTermId: 'revolutionaerem-wandel' },
      { id: 'ct2', before: ', bei geringem Druck und langem Horizont von ', correctTermId: 'evolutionaerem-wandel' },
      { id: 'ct3', before: '. Lewins Kraftfeld-Ansatz beschreibt den Wandel in drei Phasen: ', correctTermId: 'unfreezing' },
      { id: 'ct4', before: ', Changing und ', correctTermId: 'refreezing' },
    ],
    tail: '.',
    terms: [
      { id: 'revolutionaerem-wandel', text: 'revolutionärem Wandel' },
      { id: 'evolutionaerem-wandel', text: 'evolutionärem Wandel' },
      { id: 'unfreezing', text: 'Unfreezing' },
      { id: 'refreezing', text: 'Refreezing' },
    ],
    distractors: [
      { id: 'transformation', text: 'Transformation' },
      { id: 'stabilisierung', text: 'Stabilisierung' },
    ],
  },

  // ---------------------------------------------------------- STRATEGIE
  {
    id: 'swot-begriffe',
    title: 'SWOT-Analyse',
    area: 'strategie',
    difficulty: 'anfaenger',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: TEAL,
    blanks: [
      { id: 's1', before: 'Die SWOT-Analyse besteht aus einer internen und externen Betrachtung des Unternehmens. Bei der internen Analyse werden die ', correctTermId: 'staerken' },
      { id: 's2', before: ' (Strengths) und ', correctTermId: 'schwaechen' },
      { id: 's3', before: ' (Weaknesses) des Unternehmens identifiziert. Bei der externen Analyse werden die ', correctTermId: 'chancen' },
      { id: 's4', before: ' (Opportunities) und ', correctTermId: 'risiken' },
    ],
    tail: ' (Threats) des Marktumfelds untersucht.',
    terms: [
      { id: 'staerken', text: 'Stärken' },
      { id: 'schwaechen', text: 'Schwächen' },
      { id: 'chancen', text: 'Chancen' },
      { id: 'risiken', text: 'Risiken' },
    ],
    distractors: [
      { id: 'kernkompetenzen', text: 'Kernkompetenzen' },
      { id: 'marktanteile', text: 'Marktanteile' },
    ],
  },
  {
    id: 'fuenf-forces-begriffe',
    title: 'Das Five-Forces-Modell',
    area: 'strategie',
    difficulty: 'anfaenger',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: TEAL,
    blanks: [
      { id: 'ff1', before: 'Nach Porter bestimmen fünf Kräfte die Attraktivität einer Branche. Im Zentrum steht der ', correctTermId: 'branchenwettbewerb' },
      { id: 'ff2', before: '. Zusätzlich zählen die Verhandlungsmacht von ', correctTermId: 'lieferanten' },
      { id: 'ff3', before: ' und ', correctTermId: 'kunden' },
      { id: 'ff4', before: ' sowie die Gefahr durch ', correctTermId: 'neue-wettbewerber' },
    ],
    tail: ' und Substitutionsprodukte dazu.',
    terms: [
      { id: 'branchenwettbewerb', text: 'Branchenwettbewerb' },
      { id: 'lieferanten', text: 'Lieferanten' },
      { id: 'kunden', text: 'Kunden' },
      { id: 'neue-wettbewerber', text: 'neue Wettbewerber' },
    ],
    distractors: [
      { id: 'aktionaere', text: 'Aktionäre' },
      { id: 'regulierungsbehoerden', text: 'Regulierungsbehörden' },
    ],
  },
  {
    id: 'wertschoepfungskette-begriffe',
    title: 'Primäre und sekundäre Aktivitäten',
    area: 'strategie',
    difficulty: 'fortgeschritten',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: TEAL,
    blanks: [
      { id: 'wb1', before: 'Die Wertschöpfungskette unterscheidet zwischen den ', correctTermId: 'primaeren-aktivitaeten' },
      { id: 'wb2', before: ', die direkt an der Erstellung der Leistung beteiligt sind, und den ', correctTermId: 'sekundaeren-aktivitaeten' },
    ],
    tail: ', die diese Leistungserstellung abteilungsübergreifend unterstützen.',
    terms: [
      { id: 'primaeren-aktivitaeten', text: 'primären Aktivitäten' },
      { id: 'sekundaeren-aktivitaeten', text: 'sekundären Aktivitäten' },
    ],
    distractors: [
      { id: 'kernaktivitaeten', text: 'Kernaktivitäten' },
      { id: 'randaktivitaeten', text: 'Randaktivitäten' },
    ],
  },
  {
    id: 'vier-p-vier-c',
    title: '4P & 4C des Marketing-Mix',
    area: 'strategie',
    difficulty: 'fortgeschritten',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: TEAL,
    blanks: [
      { id: 'pc1', before: 'Lauternborns 4C-Konzept ergänzt McCarthys 4P: Product korrespondiert mit ', correctTermId: 'customer-needs' },
      { id: 'pc2', before: ', Price mit ', correctTermId: 'cost' },
      { id: 'pc3', before: ', Place mit ', correctTermId: 'convenience' },
    ],
    tail: ' und Promotion mit Communication.',
    terms: [
      { id: 'customer-needs', text: 'Customer needs' },
      { id: 'cost', text: 'Cost to the customer' },
      { id: 'convenience', text: 'Convenience' },
    ],
    distractors: [
      { id: 'competition', text: 'Competition' },
      { id: 'capabilities', text: 'Capabilities' },
    ],
  },
  {
    id: 'generische-strategien-begriffe',
    title: 'Die drei generischen Strategien',
    area: 'strategie',
    difficulty: 'profi',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: TEAL,
    blanks: [
      { id: 'gb1', before: 'Porter unterscheidet drei generische Strategien: Bei der ', correctTermId: 'differenzierung' },
      { id: 'gb2', before: ' wird die Leistung als einzigartig wahrgenommen, bei der ', correctTermId: 'kostenfuehrerschaft' },
      { id: 'gb3', before: ' konkurriert man über den niedrigsten Preis, und bei der ', correctTermId: 'konzentration' },
    ],
    tail: ' beschränkt man sich auf einen Nischenmarkt.',
    terms: [
      { id: 'differenzierung', text: 'Differenzierung' },
      { id: 'kostenfuehrerschaft', text: 'Kostenführerschaft' },
      { id: 'konzentration', text: 'Konzentration' },
    ],
    distractors: [
      { id: 'diversifikation', text: 'Diversifikation' },
      { id: 'kooperation', text: 'Kooperation' },
    ],
  },
  {
    id: 'gesamtkonzept-begriffe',
    title: 'Das Gesamtkonzept zur Fallstudienlösung',
    area: 'strategie',
    difficulty: 'profi',
    intro: 'Ziehe die passenden Fachbegriffe in die Lücken.',
    accent: TEAL,
    blanks: [
      { id: 'gk1', before: 'Bei primär unternehmensbezogenen Fragen wie Profitabilitätsanalysen bietet sich die ', correctTermId: 'wertschoepfungskette' },
      { id: 'gk2', before: ' als Startpunkt an. Bei Fragen zum Marktumfeld eignet sich das ', correctTermId: 'five-forces-modell' },
      { id: 'gk3', before: '. Für gemischte Fragestellungen werden interne und ', correctTermId: 'externe' },
    ],
    tail: ' Potenziale gleichzeitig betrachtet, etwa über SWOT oder das 4-C-Konzept.',
    terms: [
      { id: 'wertschoepfungskette', text: 'Wertschöpfungskette' },
      { id: 'five-forces-modell', text: 'Five-Forces-Modell' },
      { id: 'externe', text: 'externe' },
    ],
    distractors: [
      { id: 'kundenbefragung', text: 'Kundenbefragung' },
      { id: 'interne-revision', text: 'interne Revision' },
    ],
  },
];
